LINES = [
    "    return { root: missionRoot, mount: missionRoot, source: sourceNode };",
    "}",
    "",
    "function makeMissionCandidateWithoutSource(doc) {",
    "    const missionRoot = new FakeElement('form', doc);",
    "    missionRoot.setAttribute('action', '/missions/9901');",
    "    missionRoot.matchSet.add('form[action*=\"/missions/\"]');",
    "    missionRoot.selectedUnits = [];",
    "    missionRoot.enRouteRows = [];",
    "    missionRoot.queryHandler = selector => {",
    "        if (selector === '#missing_text') return missionRoot.children.find(child => child.id === 'missing_text' && child.isConnected) || null;",
    "        if (selector === '[data-mcms-requirements-anchor=\"1\"]') return missionRoot.children.find(child => child.getAttribute?.('data-mcms-requirements-anchor') === '1' && child.isConnected) || null;",
    "        return null;",
    "    };",
    "    missionRoot.queryAllHandler = selector => {",
    "        if (selector.includes('.vehicle_checkbox')) return missionRoot.selectedUnits;",
    "        if (selector === '#mission_vehicle_driving tbody tr') return missionRoot.enRouteRows;",
    "        return [];",
    "    };",
    "    return { root: missionRoot, mount: missionRoot };",
    "}",
    "",
]
PAYLOAD = "\n".join(LINES)
