"""Compose Unit Switcher with the current hospital and Home Response builds."""
import pathlib,runpy,re,json,zipfile
root=pathlib.Path(__file__).resolve().parent
runpy.run_path(str(root/'build-hospital-test.py'))
out=root.parent/'.dev/home-response-extension'
parts=[]
for file in [root/'home-response/catalogue.mjs',*[root/'unit-switcher'/name for name in ['core.mjs','native.mjs','ui.mjs']]]:
 s=file.read_text();s=re.sub(r'^import .*?;\n','',s,flags=re.M);s=re.sub(r'^export ','',s,flags=re.M);parts.append(s)
bundle='const UnitSwitcher=(()=>{\n'+'\n'.join(parts)+'\nreturn {configureSwitcher,mountSwitcher,destroySwitcher};})();\n'
p=out/'toolkit.js';s=p.read_text();anchor='const HospitalUpgrades=(()=>{';assert s.count(anchor)==1;s=s.replace(anchor,bundle+anchor);s=s.replace('HospitalUpgrades.mountHospitals(grid);','HospitalUpgrades.mountHospitals(grid);UnitSwitcher.mountSwitcher(grid);');s=s.replace('HospitalUpgrades.destroyHospitals();','HospitalUpgrades.destroyHospitals();UnitSwitcher.destroySwitcher();');s=s.replace('pilot.operations=createOperationsController({','UnitSwitcher.configureSwitcher(HomeResponseBuilder.nativeAdapter(window));\npilot.operations=createOperationsController({');p.write_text(s)
p=out/'manifest.json';m=json.loads(p.read_text());m.update(version='1.2.5',version_name='Unit Switcher testing · Extension 1.2.5 · Toolkit 10.18.1');p.write_text(json.dumps(m,indent=2)+'\n')
p=out/'BUILD.json';m=json.loads(p.read_text());m.update(extensionVersion='1.2.5',channel='unit-switcher-testing',liveValidation='Vehicle removal and replacement not live-tested');p.write_text(json.dumps(m,indent=2)+'\n')
for name in ['help.html','privacy.html','popup.html','README.md','release-notes.html']:
 p=out/name;s=p.read_text().replace('1.1.3','1.2.5');p.write_text(s)
p=out/'release-notes.html';p.write_text(p.read_text().replace('<main>','<main><h1>Home Response Unit Switcher · 1.2.5 test</h1><p>Handles explicit full-slot shops that retain disabled Credit buttons. Requires an enabled live offer after removal. Fixes Credit purchase links containing building and return_tab parameters for every supported Home Response vehicle type. Preserves native navigation parameters while validating the building, vehicle type and Credits-only route. Finds native Credit links across vehicle shop categories, including Ambulance, and recognises both scoped purchase link formats. Shows removal and purchase recovery states accurately. Faster previews: one account/building/fleet snapshot and up to four concurrent shop checks, with fresh checks before removal. Filter Home Responses by All dispatch centres or a named centre, choose a current and replacement vehicle type, select vehicles and check live shop prices. Confirm permanent removal and Credit replacement purchases. Available-at-station vehicles only; default new names. Saved progress and uncertain-request verification prevent automatic repeat purchases. Native removal controls must be offered by the game. Full single-vehicle shops may use a labelled catalogue estimate when the game explicitly reports no free space. The live purchase offer is required after removal. Live acceptance remains untested.</p>',1))
p=out/'help.html';p.write_text(p.read_text().replace('<h2>Hospital upgrades</h2>','<h2>Home Response Unit Switcher</h2><p>Open Operations, choose Unit Switcher, a dispatch centre (All includes unassigned buildings), current vehicle type and replacement type. Select vehicles, check replacements and review permanent removal and purchase costs. Only available-at-station vehicles are eligible. New vehicles use default names and may require crew training. No refund is assumed. A purchase failure after removal can leave a slot empty; Review &amp; resume continues the saved task. An uncertain request is verified without repeating it. Native controls must be available, with the replacement Credit offer verified after removal. When a single-vehicle shop explicitly reports no space and hides purchase links, a catalogue estimate is shown and acknowledged before removal. Higher live prices or unavailable replacements leave the slot awaiting replacement.</p><h2>Hospital upgrades</h2>'))
p=out/'privacy.html';p.write_text(p.read_text().replace('<h2>Your choices</h2>','<h2>Unit Switcher checkpoints</h2><p>Account-scoped site storage saves selected vehicle and Home Response IDs, building names, source and target vehicle types, dispatch scope, confirmed costs, vehicle IDs before removal, progress and verified replacement IDs. Clear MissionChief site storage to remove these plans. No analytics or external data sharing is added.</p><h2>Your choices</h2>'))
p=out/'README.md';p.write_text('# Home Response Unit Switcher — 1.2.5 test\n\nAdds dispatch filtering, selected vehicle replacement, native Credit checks and durable removal/purchase recovery. Live vehicle removal and replacement have not been tested. Includes hospital 1.1.3 fixes. Store submission remains unchanged.\n\n'+p.read_text())
archive=out.parent/'MissionChief-Toolkit-Extension-1.2.5-test.zip'
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted(out.rglob('*')):
  if p.is_file():z.writestr(zipfile.ZipInfo(str(p.relative_to(out)),(2026,1,1,0,0,0)),p.read_bytes(),compress_type=zipfile.ZIP_DEFLATED)
print(archive)
