"""Package the current 1.2.5 functionality for Chrome Web Store submission."""
import pathlib,runpy,json,zipfile,hashlib
root=pathlib.Path(__file__).resolve().parent
runpy.run_path(str(root/'build-switcher-test.py'))
out=root.parent/'.dev/home-response-extension'
p=out/'manifest.json';m=json.loads(p.read_text());m.update(version='1.2.5',version_name='Extension 1.2.5 · Toolkit 10.18.1');p.write_text(json.dumps(m,indent=2)+'\n')
p=out/'BUILD.json';m=json.loads(p.read_text());m.update(channel='stable',automatedTests=111,liveValidation='User tested previews and removal; complete replacement after latest full-slot fix remains unverified');p.write_text(json.dumps(m,indent=2)+'\n')
for name in ['popup.html','privacy.html','help.html']:
 p=out/name;s=p.read_text().replace('1.2.5 test','1.2.5').replace('Hospital upgrades testing','Hospital upgrades');p.write_text(s)
p=out/'README.md';p.write_text('# MissionChief Map Command Toolkit — 1.2.5\n\nIncludes Home Response Builder, Unit Switcher, direct hospital target-level upgrades, map controls, Operations, finance and optional Discord reports. 111 automated tests pass. Latest full-slot replacement completion remains unverified in a live account. Review costs and permanent vehicle removal before confirming.\n\nDeveloper: MartyBlyth. Helper: Conroy1988.\n')
p=out/'release-notes.html';s=p.read_text();start=s.index('<main>');end=s.index('</main>',start);s=s[:start]+'''<main><h1>Version 1.2.5</h1><h2>Home Response Unit Switcher</h2><p>Filter by All dispatch centres, a named centre or Unassigned. Choose the current and replacement vehicle types, select vehicles, check costs and confirm permanent removal and replacement. New vehicles receive game-default names. Busy vehicles are skipped. Preview checks share a fleet snapshot and run up to four shops concurrently.</p><p>Supports native Credit links and category navigation. Full single-vehicle shops can show a labelled estimate before removal; the replacement must have an enabled live Credit offer afterwards. Pause and Review &amp; resume preserve progress and verify uncertain requests without automatically repeating them.</p><h2>Hospital upgrades</h2><p>Select individual or all eligible hospitals and a target level from 1–30. Purchases use the direct native target-level action. Current balance and estimated costs are displayed separately. Completion verifies the hospital record, including maximum-level hospitals.</p><h2>Home Response Builder and Operations</h2><p>Includes city and map boundary selection, up to 1,000 proposals, spacing and water checks, nearest dispatch-centre assignment, cached building icon selection, saved build queues and stage timings. Back to Operations preserves current selections and work.</p><h2>Before running</h2><p>Confirmed operations affect your game account and spend Credits. Unit replacement permanently removes the old vehicle and can leave an empty slot if the subsequent purchase fails. Staffing and training are not automatically supplied. Keep the game tab open and review saved tasks before resuming.</p></main>'''+s[end+7:];p.write_text(s)
archive=out.parent/'MissionChief-Toolkit-Extension-1.2.5.zip'
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted(out.rglob('*')):
  if p.is_file():z.writestr(zipfile.ZipInfo(str(p.relative_to(out)),(2026,1,1,0,0,0)),p.read_bytes(),compress_type=zipfile.ZIP_DEFLATED)
print(archive);print(hashlib.sha256(archive.read_bytes()).hexdigest())
