import test from 'node:test';import assert from 'node:assert/strict';import {switchScope,switchCentres,runSwitcher} from './core.mjs';
const buildings=[{id:1,building_type:22,caption:'Home A',leitstelle_building_id:7},{id:2,building_type:22,caption:'Home B',leitstelle_building_id:null},{id:3,building_type:0},{id:7,building_type:7,caption:'Zulu'},{id:8,building_type:7,caption:'Alpha'}];
const vehicles=[{id:10,building_id:1,vehicle_type:3,fms_real:2},{id:11,building_id:2,vehicle_type:3,fms_real:3},{id:12,building_id:3,vehicle_type:3,fms_real:2}];
const make=()=>({schema:1,account:'7',dispatch:'all',to:10,ceiling:4000,spent:0,state:'ready',items:[{id:'10',buildingId:'1',from:3,state:'pending',cost:4000}]});
const fixture=()=>{let present=true,replaced=false,deletes=0,buys=0;const api={accountCheck:async()=>{},prepare:async()=>({cost:4000,before:['10']}),remove:async()=>{deletes++;present=false;},removed:async()=>!present,purchaseCheck:async()=>({cost:4000}),buy:async()=>{buys++;replaced=true;},replacement:async()=>replaced?'20':null};return {api,counts:()=>[deletes,buys],deleted:()=>present=false,replaced:()=>replaced=true};};
const save=async()=>{};
test('All includes unassigned Home Responses; named centres and source type filter precisely',()=>{assert.equal(switchScope(buildings,vehicles).length,2);assert.deepEqual(switchScope(buildings,vehicles,'7',3).map(i=>i.id),['10']);assert.equal(switchScope(buildings,vehicles,'all',10).length,0);assert.equal(switchScope(buildings,vehicles,'',3)[0].selected,false);assert.deepEqual(switchCentres(buildings).map(c=>c.name),['All dispatch centres','Alpha','Zulu','Unassigned']);});
test('replacement persists removal and purchase intents before mutations',async()=>{const f=fixture(),j=make(),saved=[];f.api.remove=async()=>{assert.equal(saved.at(-1),'removing');f.deleted();};f.api.buy=async()=>{assert.equal(saved.at(-1),'buying');f.replaced();};await runSwitcher(j,f.api,{save:async j=>saved.push(j.items[0].state)});assert.equal(j.state,'complete');assert.equal(j.spent,4000);assert.equal(j.items[0].replacementId,'20');});
test('lost deletion response recovers without deleting twice',async()=>{const f=fixture(),j=make();f.api.remove=async()=>{f.deleted();throw Error('lost');};await assert.rejects(runSwitcher(j,f.api,{save}),/lost/);assert.equal(j.items[0].state,'removing');await runSwitcher(j,f.api,{save});assert.equal(j.state,'complete');assert.equal(f.counts()[1],1);});
test('uncertain deletion with vehicle still present is never repeated',async()=>{const f=fixture(),j=make();j.items[0].state='removing';await assert.rejects(runSwitcher(j,f.api,{save}),/uncertain/);assert.deepEqual(f.counts(),[0,0]);});
test('lost purchase response is counted once on resume',async()=>{const f=fixture(),j=make();f.api.buy=async()=>{f.replaced();throw Error('lost');};await assert.rejects(runSwitcher(j,f.api,{save}),/lost/);assert.equal(j.spent,0);await runSwitcher(j,f.api,{save});assert.equal(j.spent,4000);await runSwitcher(j,f.api,{save});assert.equal(j.spent,4000);});
test('purchase failure before sending resumes from removed slot',async()=>{const f=fixture(),j=make();f.api.buy=async()=>{throw Object.assign(Error('account'),{switchNotSent:true});};await assert.rejects(runSwitcher(j,f.api,{save}),/account/);assert.equal(j.items[0].state,'removed');assert.equal(f.counts()[0],1);f.api.buy=async()=>f.replaced();await runSwitcher(j,f.api,{save});assert.equal(f.counts()[0],1);assert.equal(j.state,'complete');});
test('price increase, account change and checkpoint failure prevent removal',async()=>{for(const reason of ['price','account','storage']){const f=fixture(),j=make();if(reason==='price')f.api.prepare=async()=>({cost:4001});if(reason==='account')f.api.accountCheck=async()=>{throw Error('account');};await assert.rejects(runSwitcher(j,f.api,{save:reason==='storage'?async()=>{throw Error('storage');}:save}));assert.deepEqual(f.counts(),[0,0]);}});
test('busy vehicles skip; pause after removal leaves a resumable empty slot',async()=>{const f=fixture(),j=make();await runSwitcher(j,f.api,{save,stopped:()=>j.items[0].state==='removed'});assert.equal(j.state,'paused');assert.deepEqual(f.counts(),[1,0]);await runSwitcher(j,f.api,{save});assert.deepEqual(f.counts(),[1,1]);const other=fixture();other.api.prepare=async()=>({skip:'Busy'});await runSwitcher(make(),other.api,{save});assert.deepEqual(other.counts(),[0,0]);});

test('unacknowledged catalogue estimate stops before removal',async()=>{const f=fixture(),j=make();f.api.prepare=async()=>({cost:4000,before:['10'],estimated:true});await assert.rejects(runSwitcher(j,f.api,{save}),/catalogue estimate/);assert.deepEqual(f.counts(),[0,0]);});

test('failed replacement lookup reports the already removed vehicle accurately',async()=>{const f=fixture(),j=make();f.api.purchaseCheck=async()=>{throw Error('No matching Credit offer');};await assert.rejects(runSwitcher(j,f.api,{save}),/Vehicle removed; replacement outstanding/);assert.equal(j.items[0].state,'removed');assert.deepEqual(f.counts(),[1,0]);});
