import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {switchNative} from './native.mjs';
const require=createRequire(new URL('../home-response/package.json',import.meta.url));const {JSDOM}=require('jsdom');
function fixture({method='delete',busy=false,disabled=false,full=false,fullDisabled=false,missing=false,duplicate=false,short=false}={}){const win=new JSDOM('',{url:'https://www.missionchief.co.uk'}).window;let fleet=[{id:10,building_id:1,vehicle_type:3,fms_real:busy?3:2}],writes=[];win.fetch=async(url,opts)=>{const path=new URL(url).pathname;if(opts.method==='DELETE'){writes.push(['delete',path]);fleet=[];}else if(path.includes('/vehicle/')){writes.push(['buy',path]);fleet=[{id:20,building_id:1,vehicle_type:10,fms_real:2}];}return {ok:true,status:200,url:String(url),text:async()=>path==='/api/vehicles'?JSON.stringify(fleet):''};};
 const base={account:async()=>({user_id:7,credits_user_current:10000}),buildings:async()=>[{id:1,building_type:22,leitstelle_building_id:7}],html:async path=>({doc:new win.DOMParser().parseFromString(path.includes('/vehicles/new')?(full&&fleet.length?'<p>No free places for vehicles</p>':missing?'<p>Vehicle shop unavailable</p>':`${fullDisabled&&fleet.length?'<p>No free parking spaces</p>':''}<a ${(disabled||fullDisabled&&fleet.length)?'class="disabled"':''} href="/buildings/1/vehicle/${short?'':'1/'}10/credits">4,000 Credits</a>`.repeat(duplicate?2:1)):`<meta name="csrf-token" content="test"><a data-method="${method}" href="/vehicles/10">Delete</a>`,'text/html')})};return {api:switchNative(win,base),writes,close:()=>win.close()};}
const item=()=>({id:'10',buildingId:'1',from:3,cost:4000}),job={account:'7',dispatch:'7',to:10};
test('native deletion requires exact DELETE control; purchase verifies new vehicle ID and type',async()=>{const f=fixture(),i=item();try{const check=await f.api.prepare(i,job);i.before=check.before;await f.api.remove(i,job,check);assert.equal(await f.api.removed(i,job),true);const p=await f.api.purchaseCheck(i,job);await f.api.buy(i,job,p);assert.equal(await f.api.replacement(i,job),'20');assert.deepEqual(f.writes,[['delete','/vehicles/10'],['buy','/buildings/1/vehicle/1/10/credits']]);}finally{f.close();}});
test('missing removal method or disabled replacement offer blocks before deletion',async()=>{for(const args of [{method:'get'},{disabled:true}]){const f=fixture(args);try{await assert.rejects(f.api.prepare(item(),job));assert.equal(f.writes.length,0);}finally{f.close();}}});
test('busy vehicle and dispatch mismatch cannot be removed',async()=>{const f=fixture({busy:true});try{assert.ok((await f.api.prepare(item(),job)).skip);await assert.rejects(f.api.prepare(item(),{...job,dispatch:'8'}),/dispatch/);assert.equal(f.writes.length,0);}finally{f.close();}});

test('explicit full shop yields an estimate, then requires a live offer after removal',async()=>{const f=fixture({full:true}),i=item();try{const check=await f.api.prepare(i,job);assert.equal(check.estimated,true);assert.equal(check.cost,4000);assert.equal(check.url,undefined);i.before=check.before;await f.api.remove(i,job,check);const live=await f.api.purchaseCheck(i,job);assert.equal(live.estimated,false);await f.api.buy(i,job,live);assert.equal(await f.api.replacement(i,job),'20');}finally{f.close();}});
test('unexplained missing shop offers never permit removal',async()=>{const f=fixture({missing:true});try{await assert.rejects(f.api.prepare(item(),job),/No matching/);assert.equal(f.writes.length,0);}finally{f.close();}});
test('identical repeated purchase links are one offer',async()=>{const f=fixture({duplicate:true});try{assert.equal((await f.api.prepare(item(),job)).cost,4000);}finally{f.close();}});

test('short native purchase link remains bound to the correct building and type',async()=>{const f=fixture({short:true});try{const check=await f.api.prepare(item(),job);assert.equal(check.url,'https://www.missionchief.co.uk/buildings/1/vehicle/10/credits');assert.equal(check.cost,4000);}finally{f.close();}});
test('shop follows native Ambulance category navigation to find the Credit offer',async()=>{const win=new JSDOM('',{url:'https://www.missionchief.co.uk'}).window,paths=[];win.fetch=async url=>({ok:true,status:200,url:String(url),text:async()=>JSON.stringify([{id:10,building_id:1,vehicle_type:3,fms_real:2}])});const base={account:async()=>({user_id:7,credits_user_current:10000}),buildings:async()=>[{id:1,building_type:22,leitstelle_building_id:7}],html:async path=>{paths.push(path);const text=path==='/vehicles/10'?'<meta name="csrf-token" content="test"><a data-method="delete" href="/vehicles/10">Delete</a>':path.includes('?group=ambulance')?'<a href="/buildings/1/vehicle/10/credits">4,000 Credits</a>':'<a href="/buildings/1/vehicles/new?group=ambulance">Ambulance</a><a href="https://unrelated.invalid/buildings/1/vehicles/new?x=1">Police</a>';return {doc:new win.DOMParser().parseFromString(text,'text/html')};}};try{const check=await switchNative(win,base).prepare(item(),job);assert.equal(check.cost,4000);assert.ok(paths.some(p=>p.endsWith('?group=ambulance')));assert.ok(paths.every(p=>!p.includes('unrelated')));}finally{win.close();}});

test('explicit full-slot disabled offer can be estimated, then must become enabled after removal',async()=>{const f=fixture({fullDisabled:true}),i=item();try{const check=await f.api.prepare(i,job);assert.equal(check.estimated,true);assert.equal(check.cost,4000);assert.equal(check.url,undefined);i.before=check.before;await f.api.remove(i,job,check);const purchase=await f.api.purchaseCheck(i,job);assert.equal(purchase.estimated,false);await f.api.buy(i,job,purchase);assert.equal(await f.api.replacement(i,job),'20');}finally{f.close();}});
test('persistently disabled replacement is never purchased after removal',async()=>{const f=fixture({fullDisabled:true,disabled:true}),i=item();try{const check=await f.api.prepare(i,job);i.before=check.before;await f.api.remove(i,job,check);await assert.rejects(f.api.purchaseCheck(i,job),/disabled/);assert.equal(f.writes.length,1);assert.equal(f.writes[0][0],'delete');}finally{f.close();}});
