import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {switchNative} from './native.mjs';
const require=createRequire(new URL('../home-response/package.json',import.meta.url));const {JSDOM}=require('jsdom');
function fixture({bad=false}={}){const w=new JSDOM('',{url:'https://www.missionchief.co.uk'}).window;const items=Array.from({length:20},(_,n)=>({id:String(n+100),buildingId:String(n+1),from:3,name:`Home ${n+1}`}));let accounts=0,catalogues=0,fleets=0,pages=0,active=0,peak=0;
 w.fetch=async url=>{fleets++;return {ok:true,status:200,url:String(url),text:async()=>JSON.stringify(items.map(i=>({id:i.id,building_id:i.buildingId,vehicle_type:3,fms_real:2})))};};
 const base={account:async()=>{accounts++;return {user_id:7,credits_user_current:100000};},buildings:async()=>{catalogues++;return items.map(i=>({id:i.buildingId,building_type:22}));},html:async path=>{assert.match(path,/\/buildings\/\d+\/vehicles\/new$/);pages++;active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,5));active--;if(bad&&path.includes('/1/'))throw Error('Shop failed');const id=path.split('/')[2];return {doc:new w.DOMParser().parseFromString(`<a href="/buildings/${id}/vehicle/${id}/10/credits">4,000 Credits</a>`,'text/html')};}};
 return {api:switchNative(w,base),items,counts:()=>({accounts,catalogues,fleets,pages,active,peak}),close:()=>w.close()};}
const job={account:'7',dispatch:'all',to:10};
test('preview reads account and catalogues once and checks four shops concurrently',async()=>{const f=fixture();try{const done=[];const results=await f.api.quoteBatch(f.items,job,{progress:n=>done.push(n)});assert.equal(results.length,20);assert.ok(results.every(r=>r.cost===4000));assert.deepEqual(f.counts(),{accounts:1,catalogues:1,fleets:1,pages:20,active:0,peak:4});assert.equal(done.at(-1),20);}finally{f.close();}});
test('paused preview drains in-flight requests and starts no further shops',async()=>{const f=fixture();let stop=false;try{await assert.rejects(f.api.quoteBatch(f.items,job,{stopped:()=>stop,progress:()=>stop=true}),/paused/);assert.equal(f.counts().active,0);assert.equal(f.counts().pages,4);}finally{f.close();}});
test('shop error drains active reads and returns no purchase plan',async()=>{const f=fixture({bad:true});try{await assert.rejects(f.api.quoteBatch(f.items,job),/Home 1: Shop failed/);assert.equal(f.counts().active,0);assert.equal(f.counts().pages,4);}finally{f.close();}});
test('account mismatch stops before shop requests',async()=>{const f=fixture();try{await assert.rejects(f.api.quoteBatch(f.items,{...job,account:'8'}),/account/);assert.equal(f.counts().pages,0);}finally{f.close();}});
