import {switchScope,switchCentres,runSwitcher} from './core.mjs';
import {switchNative} from './native.mjs';
import {VEHICLES} from '../home-response/catalogue.mjs';
let switchDialog,switchStop=false,switchBusy=false,switchBase;
export function configureSwitcher(base){switchBase=base;}
export function destroySwitcher(){switchStop=true;switchDialog?.remove();}
export function mountSwitcher(grid){if(grid.querySelector('[data-unit-switcher]'))return;const b=document.createElement('button');b.dataset.unitSwitcher='';for(const [tag,text]of [['strong','Home Response Unit Switcher'],['span','Replace a vehicle type across selected Home Responses.']]){const el=document.createElement(tag);el.textContent=text;b.append(el);}b.onclick=openSwitcher;grid.append(b);}
function openSwitcher(){
 if(switchDialog?.isConnected){switchDialog.showModal();return;}if(!switchBase)return;
 const d=document.createElement('dialog');switchDialog=d;d.className='tkb-switcher';
 d.innerHTML=`<style>.tkb-switcher{background:#141619;color:#eee;border:1px solid #666;border-top:3px solid #e33;border-radius:8px;padding:18px;width:min(1000px,94vw);max-height:90dvh;font:14px/1.5 system-ui}.tkb-switcher::backdrop{background:#000a}.tkb-switcher header,.tkb-switcher .controls{display:flex;flex-wrap:wrap;align-items:center;gap:10px}.tkb-switcher header{justify-content:space-between;position:sticky;top:-18px;background:#141619;z-index:2;padding:8px 0}.tkb-switcher h2{color:#fff;margin:0}.tkb-switcher label{display:flex;flex-direction:column;gap:4px}.tkb-switcher button,.tkb-switcher select{background:#282b30;color:#fff!important;border:1px solid #777;border-radius:4px;padding:8px;font:inherit;min-height:40px}.tkb-switcher button:disabled{opacity:.45}.tkb-switcher output{display:block;background:#24282d;color:#fff!important;padding:10px;margin:12px 0}.tkb-switcher .scroll{max-height:40dvh;overflow:auto;margin:12px 0}.tkb-switcher table{width:100%;border-collapse:collapse}.tkb-switcher th,.tkb-switcher td{padding:8px;text-align:left;border-bottom:1px solid #444}.tkb-switcher input{appearance:auto;width:18px;height:18px}.tkb-switcher [data-run]{background:#8b2028}</style>
 <header><h2>Home Response Unit Switcher</h2><button data-close>← Back to Operations</button></header>
 <p>Replace one vehicle type across your Home Responses. Only vehicles available at their station can be selected. New vehicles receive the game’s default names.</p>
 <div class="controls"><label>Dispatch centre<select data-dispatch><option value="all">All dispatch centres</option></select></label><button data-scan>Refresh buildings & vehicles</button><label>Replace vehicle type<select data-from></select></label><label>Replacement type<select data-to></select></label></div>
 <p data-training></p><div class="controls"><button data-all>Select all eligible</button><button data-none>Clear selection</button><button data-preview>Check selected replacements</button></div>
 <output data-status role="status">Loading your Home Responses and dispatch centres…</output>
 <div class="scroll"><table><thead><tr><th>Select</th><th>Home Response</th><th>Current vehicle type</th><th>Status</th></tr></thead><tbody></tbody></table></div>
 <p>Replacing removes the existing vehicle permanently, then purchases its replacement with Credits. No refund is included in the estimate. Crew training may be required. A failed purchase can leave a slot empty until you resume.</p>
 <div class="controls"><button data-run disabled>Review & replace</button><button data-pause disabled>Pause after current request</button><button data-resume disabled>Review & resume</button></div>`;
 document.body.append(d);d.showModal();const $=s=>d.querySelector(s),api=switchNative(window,switchBase);let buildings=[],vehicles=[],rows=[],job=null,quote=null,account='';
 const name=id=>VEHICLES.find(v=>v.id===Number(id))?.name||`Vehicle type ${id}`;
 const say=s=>$('[data-status]').textContent=s;
 const key=()=>`mcms_hr_unit_switcher_${account}`;
 const save=async j=>{const text=JSON.stringify(j);localStorage.setItem(key(),text);if(localStorage.getItem(key())!==text)throw Error('Could not save replacement progress.');render();};
 const render=()=>{const body=$('tbody');body.replaceChildren();for(const r of job?.items||rows){const tr=document.createElement('tr'),td=document.createElement('td'),c=document.createElement('input');c.type='checkbox';c.checked=Boolean(r.selected);c.disabled=switchBusy||Boolean(job)||r.state==='unavailable';c.setAttribute('aria-label',`Select ${r.name} vehicle ${r.id}`);c.onchange=()=>{r.selected=c.checked;quote=null;render();};td.append(c);tr.append(td);for(const t of [r.name,name(r.from),job?(r.error||({removed:'Vehicle removed — replacement outstanding',removing:'Verifying removal',buying:'Verifying purchase',complete:'Replacement complete',pending:'Pending',unavailable:'Unavailable'})[r.state]||r.state):(r.detail||r.state)]){const e=document.createElement('td');e.textContent=t;if(t===r.name){e.replaceChildren();const a=document.createElement('a');a.textContent=r.name;a.href=`/buildings/${r.buildingId}/vehicles/new`;a.target='_blank';a.rel='noopener noreferrer';a.style.color='#f5d9db';e.append(a);}tr.append(e);}body.append(tr);}for(const s of ['dispatch','from','to','all','none','preview'])$('[data-'+s+']').disabled=switchBusy||Boolean(job);$('[data-scan]').disabled=switchBusy;$('[data-run]').disabled=switchBusy||!quote||Boolean(job);$('[data-resume]').disabled=switchBusy||!job||job.state==='complete';$('[data-pause]').disabled=!switchBusy;};
 const guard=async fn=>{if(switchBusy)return;switchBusy=true;switchStop=false;render();try{if(!navigator.locks?.request)throw Error('This browser cannot lock replacement tasks across tabs.');await navigator.locks.request('mcms-hospital-upgrades',{ifAvailable:true},async lock=>{if(!lock)throw Error('Another administration task is running in another tab.');await fn();});}catch(e){say(e.message);}finally{switchBusy=false;render();}};
 const identity=async()=>{const a=await api.account();if(account&&account!==String(a.user_id))throw Error('Game account changed.');account=String(a.user_id);};
 const choose=()=>{quote=null;rows=switchScope(buildings,vehicles,$('[data-dispatch]').value,$('[data-from]').value===''?null:Number($('[data-from]').value));const to=Number($('[data-to]').value),v=VEHICLES.find(v=>v.id===to);$('[data-training]').textContent=v?`${v.name}: ${v.training||'Check staffing requirements in the game.'}`:'';say(`${rows.length} matching vehicles · ${rows.filter(r=>r.selected).length} available at station. Check replacements for current prices and eligibility.`);render();};
 const types=()=>{const old=$('[data-from]').value;$('[data-from]').replaceChildren();const ids=[...new Set(switchScope(buildings,vehicles,$('[data-dispatch]').value).map(r=>r.from))].sort((a,b)=>name(a).localeCompare(name(b)));for(const id of ids)$('[data-from]').add(new Option(name(id),String(id)));if(ids.includes(Number(old)))$('[data-from]').value=old;choose();};
 const scan=async()=>{await identity();const stored=localStorage.getItem(key());if(stored){const old=JSON.parse(stored);if(old.state!=='complete'&&old.items?.some(i=>['removing','removed','buying'].includes(i.state)))throw Error('A replacement is outstanding. Use Review & resume before making a new plan.');}job=null;quote=null;[buildings,vehicles]=await Promise.all([api.buildings(),api.fleet()]);const selected=$('[data-dispatch]').value;$('[data-dispatch]').replaceChildren();for(const c of switchCentres(buildings))$('[data-dispatch]').add(new Option(c.name,c.id));if(switchCentres(buildings).some(c=>c.id===selected))$('[data-dispatch]').value=selected;types();};
 for(const v of VEHICLES)$('[data-to]').add(new Option(v.name,String(v.id)));
 $('[data-close]').onclick=()=>d.close();$('[data-pause]').onclick=()=>{switchStop=true;say('Pausing after the current request…');};$('[data-scan]').onclick=()=>guard(scan);$('[data-dispatch]').onchange=types;$('[data-from]').onchange=choose;$('[data-to]').onchange=choose;
 $('[data-all]').onclick=()=>{for(const r of rows)r.selected=r.state!=='unavailable';quote=null;render();};$('[data-none]').onclick=()=>{for(const r of rows)r.selected=false;quote=null;render();};
 $('[data-preview]').onclick=()=>guard(async()=>{await identity();quote=null;const to=Number($('[data-to]').value),selected=rows.filter(r=>r.selected);if(!selected.length)throw Error('Select vehicles to replace.');if(selected.some(r=>r.from===to))throw Error('Choose a different replacement type.');const items=[];let total=0;say(`Loading account and fleet once for ${selected.length} vehicles…`);const checks=await api.quoteBatch(selected,{account,to,dispatch:$('[data-dispatch]').value},{stopped:()=>switchStop,progress:(done,total,r)=>say(`Checked ${done}/${total}: ${r.name} · up to 4 shops at once`)});for(const [index,r]of selected.entries()){const check=checks[index];if(check.skip){r.state='unavailable';r.selected=false;r.detail=check.skip;continue;}r.cost=check.cost;r.estimated=Boolean(check.estimated);r.detail=check.estimated?'Estimated: shop has no free slot':`${check.cost.toLocaleString()} Credits`;total+=check.cost;items.push({...r});}if(!items.length)throw Error('No available vehicles remain.');quote={schema:1,account,dispatch:$('[data-dispatch]').value,to,ceiling:total,spent:0,state:'ready',items};say(`${items.length} replacements · ${total.toLocaleString()} Credits · ${name(to)}. ${items.filter(i=>i.estimated).length} use catalogue estimates because the shop has no free slot. Live prices are checked after removal; higher prices pause. Removal controls are rechecked before each replacement. No removal has happened yet.`);});
 const confirm=j=>window.confirm(`Permanently remove ${j.items.filter(i=>i.state==='pending').length} selected vehicles and replace with ${name(j.to)}?\nDispatch centre: ${switchCentres(buildings).find(c=>c.id===j.dispatch)?.name||j.dispatch}\n${j.items.filter(i=>i.estimated).length} replacements use catalogue estimates because their shops have no free slot. Their live price and availability will be checked after removal; a higher price or unavailable unit leaves the slot awaiting replacement.\nRemaining purchase limit: ${(j.ceiling-j.spent).toLocaleString()} Credits.\nNo refund assumed. New names are assigned by the game. Crew may require training.\nOutstanding removals and purchases will be verified before continuing.`);
 const execute=async()=>{await runSwitcher(job,api,{save,stopped:()=>switchStop});say(`${job.state}: ${job.items.filter(i=>i.state==='complete').length}/${job.items.length} replaced · ${job.spent.toLocaleString()} Credits spent.`);};
 $('[data-run]').onclick=()=>guard(async()=>{await identity();if(!quote||!confirm(quote))return;job=quote;quote=null;await save(job);await execute();});
 $('[data-resume]').onclick=()=>guard(async()=>{await identity();job=JSON.parse(localStorage.getItem(key()));if(!job||!confirm(job))return;await execute();});
 guard(async()=>{await identity();const saved=localStorage.getItem(key());if(saved){job=JSON.parse(saved);[buildings,vehicles]=await Promise.all([api.buildings(),api.fleet()]);$('[data-dispatch]').replaceChildren();for(const c of switchCentres(buildings))$('[data-dispatch]').add(new Option(c.name,c.id));$('[data-dispatch]').value=job.dispatch;$('[data-to]').value=String(job.to);say(`Saved ${job.state} plan. Review & resume to continue.`);}else await scan();});
}
