export default [
  {
    files: ["src/MissionChief_Map_Command_Toolkit.user.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script"
    },
    linterOptions: {
      reportUnusedDisableDirectives: "warn"
    },
    rules: {
      "complexity": ["warn", { "max": 40 }],
      "max-depth": ["warn", 6],
      "max-lines-per-function": ["warn", { "max": 220, "skipBlankLines": true, "skipComments": true, "IIFEs": false }],
      "max-params": ["warn", 9],
      "no-async-promise-executor": "error",
      "no-await-in-loop": "warn",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "except-parens"],
      "no-constant-binary-expression": "error",
      "no-constant-condition": ["warn", { "checkLoops": "allExceptWhileTrue" }],
      "no-constructor-return": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "warn",
      "no-fallthrough": ["error", { "commentPattern": "falls?\\s?through" }],
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-new-native-nonconstructor": "error",
      "no-obj-calls": "error",
      "no-promise-executor-return": "error",
      "no-prototype-builtins": "warn",
      "no-self-assign": "error",
      "no-self-compare": "warn",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "warn",
      "no-unassigned-vars": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "warn",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": ["warn", {
        "vars": "all",
        "args": "after-used",
        "ignoreRestSiblings": true,
        "caughtErrors": "none",
        "argsIgnorePattern": "^_",
        "varsIgnorePattern": "^_"
      }],
      "no-useless-assignment": "warn",
      "no-useless-backreference": "error",
      "no-useless-catch": "warn",
      "no-useless-escape": "warn",
      "no-with": "error",
      "require-atomic-updates": "warn",
      "use-isnan": "error",
      "valid-typeof": ["error", { "requireStringLiterals": true }]
    }
  }
];
