#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.resolve(__dirname,'..','..');const source=fs.readFileSync(path.join(root,'src','MissionChief_Map_Command_Toolkit.user.js'),'utf8');
function extractFunction(name){const marker=`    function ${name}(`;const start=source.indexOf(marker);assert.ok(start>=0,`${name} missing`);const signatureEnd=source.indexOf(') {',start);assert.ok(signatureEnd>=0,`${name} signature is malformed`);const open=source.indexOf('{',signatureEnd);let depth=0,quote='',escaped=false;for(let i=open;i<source.length;i++){const c=source[i];if(quote){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c===quote)quote='';continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw new Error(`Could not extract ${name}`);}
const functions=['majorIncidentFeedEntryCount','majorIncidentFeedSyncControls','majorIncidentFeedApplyIndex','majorIncidentFeedAnimation','majorIncidentFeedSyncReelState','majorIncidentFeedSetExpanded','refreshMajorIncidentFeedMotion'];
function classList(){return{values:new Set(),toggle(n,on){if(on)this.values.add(n);else this.values.delete(n);},contains(n){return this.values.has(n);},add(n){this.values.add(n);},remove(n){this.values.delete(n);}};}
function button(){return{disabled:false,attrs:{},textContent:'',title:'',setAttribute(n,v){this.attrs[n]=String(v);}};}
const animation={animationName:'mcmsIncidentWireReel',currentTime:0,playState:'running',effect:{getTiming:()=>({duration:12000})},play(){this.playState='running';},pause(){this.playState='paused';}};
const firstGroup={scrollWidth:2400,getBoundingClientRect:()=>({width:2400})};const viewport={};
const trackStyle={values:new Map(),setProperty(name,value){this.values.set(name,String(value));},removeProperty(name){this.values.delete(name);}};
const track={offsetWidth:2400,style:trackStyle,getAnimations:()=>[animation],querySelector(selector){return selector==='.mcms-incident-feed-group'?firstGroup:null;}};
const feedStyle={values:new Map(),setProperty(name,value){this.values.set(name,String(value));}};
const counter={textContent:''};const panel={hidden:true};const expand=button();
const feed={isConnected:true,style:feedStyle,dataset:{mcmsEntryCount:'3'},classList:classList(),querySelector(selector){if(selector==='.mcms-incident-feed-track')return track;if(selector==='.mcms-incident-feed-viewport')return viewport;if(selector==='.mcms-incident-feed-count')return counter;if(selector==='.mcms-incident-feed-panel')return panel;if(selector.includes('data-mcms-incident-action="expand"'))return expand;return null;},querySelectorAll(){return[];}};
const sandbox={console,Date,Math,Number,Boolean,String,document:{hidden:false},state:{economyMode:false,majorIncidentFeed:{enabled:true}},majorIncidentFeedCurrentIndex:0,majorIncidentFeedManualPaused:false,majorIncidentFeedExpanded:false,majorIncidentFeedMotionRevision:0,majorIncidentFeedMotionTimer:null,runtimeClearTimeout(){},runtimeSetTimeout(){throw new Error('Unexpected delayed retry');},clamp(value,minimum,maximum,fallback){const number=Number(value);return Number.isFinite(number)?Math.min(maximum,Math.max(minimum,number)):fallback;}};
vm.createContext(sandbox);vm.runInContext(`${functions.map(extractFunction).join('\n\n')}\nthis.api={${functions.join(',')}};`,sandbox);const api=sandbox.api;
assert.equal(api.majorIncidentFeedEntryCount(feed),3);api.majorIncidentFeedSyncControls(feed);assert.equal(counter.textContent,'3 LIVE');
const ensureStart=source.indexOf('    function ensureMajorIncidentFeed(');const renderStart=source.indexOf('    function renderMajorIncidentFeed(',ensureStart);const ensure=source.slice(ensureStart,renderStart);const templateStart=ensure.indexOf('feed.innerHTML = `');const templateEnd=ensure.indexOf('`;',templateStart);const template=ensure.slice(templateStart,templateEnd);assert.equal(template.includes('data-mcms-incident-action="previous"'),false);assert.equal(template.includes('data-mcms-incident-action="pause"'),false);assert.equal(template.includes('data-mcms-incident-action="next"'),false);assert.equal(template.includes('data-mcms-incident-action="expand"'),true);
api.majorIncidentFeedSetExpanded(feed,true);assert.equal(panel.hidden,false);assert.equal(animation.playState,'paused');assert.equal(expand.attrs['aria-expanded'],'true');
api.majorIncidentFeedSetExpanded(feed,false);assert.equal(panel.hidden,true);assert.equal(animation.playState,'running');assert.equal(expand.attrs['aria-expanded'],'false');
feed.classList.add('mcms-feed-interacting');api.majorIncidentFeedSyncReelState(feed);assert.equal(animation.playState,'paused');feed.classList.remove('mcms-feed-interacting');api.majorIncidentFeedSyncReelState(feed);assert.equal(animation.playState,'running');
for(const currentTime of [1750,3900,6250,9100]){animation.currentTime=currentTime;assert.equal(api.refreshMajorIncidentFeedMotion(feed,false),true);assert.equal(animation.currentTime,currentTime,'ordinary reconciliation must preserve live reel time');}
sandbox.majorIncidentFeedCurrentIndex=2;animation.currentTime=10750;assert.equal(api.refreshMajorIncidentFeedMotion(feed,true),true);assert.equal(animation.currentTime,8000,'forced content rebuild must re-anchor to retained incident index');
console.log('Issue #599 runtime passed: continuous reel reconciliation never rewinds and forced rebuild seeking remains deterministic.');
