import test from 'node:test';import assert from 'node:assert/strict';import {hospitalPlan,hospitalTarget,runHospitalUpgrades} from './core.mjs';
const make=()=>({account:'7',target:3,ceiling:300,spent:0,state:'ready',items:[{id:'1',name:'Hospital',level:0,target:3,unitPrice:100,purchased:0,spent:0}]});
const fixture=()=>{let level=0,writes=0;const api={account:async()=>({user_id:7,credits_user_current:10000}),inspect:async()=>({record:{level},operation:{priceCredits:100}}),apply:async()=>{writes++;level++;}};return {api,writes:()=>writes,setLevel:n=>level=n};};
const save=async()=>{};
test('targets and hospital-only selection skip higher levels',()=>{assert.equal(hospitalTarget('max'),30);assert.throws(()=>hospitalTarget(31));const rows=hospitalPlan([{id:1,typeId:4,caption:'A',level:4},{id:2,typeId:4,caption:'B',level:0},{id:3,typeId:0,level:0}],3);assert.equal(rows.length,2);assert.equal(rows[0].steps,0);assert.equal(rows[0].selected,false);assert.equal(rows[1].steps,3);});
test('sequential upgrades persist intent and verify each level',async()=>{const j=make(),f=fixture();f.api.apply=async()=>{assert.ok(j.items[0].intent);f.setLevel(j.items[0].intent.from+1);};await runHospitalUpgrades(j,f.api,{save});assert.equal(j.state,'complete');assert.equal(j.spent,300);assert.equal(j.items[0].purchased,3);});
test('pause and resume do not repeat completed levels',async()=>{const j=make(),f=fixture();await runHospitalUpgrades(j,f.api,{save,stopped:()=>j.items[0].purchased===1});assert.equal(j.state,'paused');await runHospitalUpgrades(j,f.api,{save});assert.equal(f.writes(),3);});
test('changed account prevents purchases',async()=>{const f=fixture();f.api.account=async()=>({user_id:8,credits_user_current:10000});await assert.rejects(runHospitalUpgrades(make(),f.api,{save}),/account/);assert.equal(f.writes(),0);});
test('changed price stops before purchase',async()=>{const f=fixture();f.api.inspect=async()=>({record:{level:0},operation:{priceCredits:101}});await assert.rejects(runHospitalUpgrades(make(),f.api,{save}),/price/);assert.equal(f.writes(),0);});
test('insufficient Credits stops before purchase',async()=>{const f=fixture();f.api.account=async()=>({user_id:7,credits_user_current:99});await assert.rejects(runHospitalUpgrades(make(),f.api,{save}),/Insufficient/);assert.equal(f.writes(),0);});
test('uncertain unchanged purchase is never replayed',async()=>{const j=make(),f=fixture();j.items[0].intent={from:0,cost:100};await assert.rejects(runHospitalUpgrades(j,f.api,{save}),/uncertain/);assert.equal(f.writes(),0);});
test('verified uncertain purchase is counted once then resumed',async()=>{const j=make(),f=fixture();j.items[0].intent={from:0,cost:100};f.setLevel(1);await runHospitalUpgrades(j,f.api,{save});assert.equal(f.writes(),2);assert.equal(j.spent,300);await runHospitalUpgrades(j,f.api,{save});assert.equal(j.spent,300);assert.equal(f.writes(),2);});
test('checkpoint failure prevents mutation',async()=>{const j=make(),f=fixture();await assert.rejects(runHospitalUpgrades(j,f.api,{save:async()=>{throw Error('storage');}}),/storage/);assert.equal(f.writes(),0);});
test('missing native action pauses rather than claims maximum',async()=>{const j=make(),f=fixture();f.api.inspect=async()=>({record:{level:0},operation:null});await assert.rejects(runHospitalUpgrades(j,f.api,{save}),/unavailable/);assert.equal(j.state,'paused');assert.equal(f.writes(),0);});
test('lost response keeps purchase intent for recovery',async()=>{const j=make(),f=fixture();f.api.apply=async()=>{f.setLevel(1);throw Error('lost response');};await assert.rejects(runHospitalUpgrades(j,f.api,{save}),/lost response/);assert.deepEqual(j.items[0].intent,{from:0,to:1,cost:100});assert.equal(j.spent,0);});
test('invalid saved price and duplicate IDs rejected',async()=>{const f=fixture(),j=make();delete j.items[0].unitPrice;await assert.rejects(runHospitalUpgrades(j,f.api,{save}),/checkpoint/);const other=make();other.items.push({...other.items[0]});await assert.rejects(runHospitalUpgrades(other,f.api,{save}),/plan/);});

test('real game balance field accepts 255 million numeric and numeric-string values',async()=>{for(const balance of [255501915,'255501915']){const f=fixture();f.api.account=async()=>({user_id:7,credits_user_current:balance,credits:0});const j=make();await runHospitalUpgrades(j,f.api,{save});assert.equal(f.writes(),3);assert.equal(j.state,'complete');}});
test('missing or malformed native balance is not described as insufficient funds',async()=>{for(const balance of [undefined,null,'',false,'abc',Infinity,-1]){const f=fixture();f.api.account=async()=>({user_id:7,credits_user_current:balance,credits:255501915});await assert.rejects(runHospitalUpgrades(make(),f.api,{save}),/Could not read your Credit balance/);assert.equal(f.writes(),0);}});

test('direct target purchases reach level 30 in one request from 0, 1 and 10',async()=>{for(const start of [0,1,10]){const j=make();j.target=30;j.ceiling=(30-start)*100;Object.assign(j.items[0],{level:start,target:30,quotedPrice:j.ceiling});let level=start,writes=0;const api={account:async()=>({user_id:7,credits_user_current:255000000}),inspect:async()=>({record:{level},operation:{targetLevel:30,priceCredits:(30-level)*100}}),apply:async()=>{assert.equal(j.items[0].intent.to,30);writes++;level=30;}};await runHospitalUpgrades(j,api,{save});assert.equal(writes,1);assert.equal(j.state,'complete');assert.equal(j.spent,j.ceiling);}});
test('direct target interrupted purchase reconciles without another purchase',async()=>{const j=make();j.items[0].intent={from:0,to:3,cost:300};const f=fixture();f.setLevel(3);await runHospitalUpgrades(j,f.api,{save});assert.equal(f.writes(),0);assert.equal(j.spent,300);});
test('partial target result stays uncertain and is never replayed',async()=>{const j=make();j.items[0].intent={from:0,to:3,cost:300};const f=fixture();f.setLevel(1);await assert.rejects(runHospitalUpgrades(j,f.api,{save}),/uncertain/);assert.equal(f.writes(),0);});
