import {hospitalCreditBalance,hospitalPlan,hospitalTarget,runHospitalUpgrades,HOSPITAL_LEVEL_LIMIT} from './core.mjs';
let hospitalBridge,hospitalDialog,hospitalStop=false,hospitalBusy=false;
export function configureHospitals(bridge){hospitalBridge=bridge;}
export function destroyHospitals(){hospitalStop=true;hospitalDialog?.remove();}
export function mountHospitals(grid){
 if(grid.querySelector('[data-hospital-upgrades]'))return;
 const b=document.createElement('button');b.type='button';b.dataset.hospitalUpgrades='';
 for(const [tag,text] of [['strong','Hospital upgrades'],['span','Choose hospitals and a target level. Preview Credit costs before upgrading.'],['small','Levels only']]){const el=document.createElement(tag);el.textContent=text;b.append(el);}
 b.onclick=()=>openHospitals();grid.append(b);
}
function openHospitals(){
 if(hospitalDialog?.isConnected){hospitalDialog.showModal();return;}
 if(!hospitalBridge)return;
 const d=document.createElement('dialog');hospitalDialog=d;d.className='tkb-hospital-upgrades';
 d.innerHTML=`<style>.tkb-hospital-upgrades{background:#121416;color:#eee;border:1px solid #555;border-top:3px solid #e22;border-radius:8px;width:min(1000px,94vw);max-height:90dvh;padding:18px;font:14px/1.5 system-ui;box-sizing:border-box}.tkb-hospital-upgrades::backdrop{background:#000a}.tkb-hospital-upgrades header,.tkb-hospital-upgrades .actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.tkb-hospital-upgrades header{justify-content:space-between;position:sticky;top:-18px;background:#121416;z-index:1;padding:8px 0}.tkb-hospital-upgrades h2{margin:0;color:#fff}.tkb-hospital-upgrades button,.tkb-hospital-upgrades select,.tkb-hospital-upgrades input{color:#fff!important;background:#25282b;border:1px solid #666;border-radius:4px;padding:8px;min-height:40px;font:inherit}.tkb-hospital-upgrades button:disabled{opacity:.45}.tkb-hospital-upgrades input[type=checkbox]{min-height:18px;width:18px;height:18px;appearance:auto}.tkb-hospital-upgrades .table-wrap{max-height:45dvh;overflow:auto;margin:12px 0}.tkb-hospital-upgrades table{width:100%;border-collapse:collapse;white-space:nowrap}.tkb-hospital-upgrades td,.tkb-hospital-upgrades th{padding:8px;text-align:left;border-bottom:1px solid #393d40}.tkb-hospital-upgrades output{color:#f5f5f5!important;opacity:1!important;display:block;padding:10px;background:#202428;margin:12px 0}.tkb-hospital-upgrades .primary{background:#941a21}.tkb-hospital-upgrades :focus-visible{outline:2px solid #f55;outline-offset:2px}</style>
 <header><h2>Hospital upgrades</h2><button data-close>← Back to Operations</button></header>
 <p>Select all hospitals or choose individual ones. Hospitals already at or above the target are skipped. Credits only.</p>
 <div class="actions"><label>Target level <select data-target><option value="max">Maximum (30)</option></select></label><button data-scan>Load hospitals</button><button data-all>Select all eligible</button><button data-none>Clear selection</button></div>
 <p>Targets 1–30 cover the observed UK hospital levels. Each purchase must still be offered by the game. If the game limit or price changes, the run pauses.</p>
 <output data-status role="status">Load your hospitals to begin.</output><div class="table-wrap"><table><thead><tr><th>Select</th><th>Hospital</th><th>Current</th><th>Target</th><th>Levels needed</th><th>Status</th></tr></thead><tbody></tbody></table></div>
 <div class="actions"><button data-preview>Preview selected costs</button><button data-run class="primary" disabled>Review & upgrade</button><button data-pause disabled>Pause after current request</button><button data-resume disabled>Review & resume</button></div><p>Cost estimates use each hospital’s current native target-level price. A higher price pauses the run. Keep this game tab open. Closing this panel preserves progress.</p>`;
 document.body.append(d);d.showModal();const $=s=>d.querySelector(s);let rows=[],job=null,accountId='',quote=null;
 for(let n=1;n<=HOSPITAL_LEVEL_LIMIT;n++)$('[data-target]').add(new Option(String(n),String(n)));
 const say=t=>$('[data-status]').textContent=t;
 const key=()=>`mcms_hospital_upgrade_job_${accountId}`;
 const save=async j=>{const value=JSON.stringify(j);localStorage.setItem(key(),value);if(localStorage.getItem(key())!==value)throw Error('Could not save upgrade progress.');render();};
 const render=()=>{const tbody=$('tbody');tbody.replaceChildren();for(const r of job?job.items:rows){const tr=document.createElement('tr'),td=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.checked=Boolean(r.selected);check.disabled=hospitalBusy||Boolean(job)||!r.steps;check.setAttribute('aria-label',`Select ${r.name}`);check.onchange=()=>{r.selected=check.checked;quote=null;$('[data-run]').disabled=true;};td.append(check);tr.append(td);for(const text of [r.name,r.level,r.target,Math.max(0,r.target-r.level),r.state]){const cell=document.createElement('td');cell.textContent=String(text);tr.append(cell);}tbody.append(tr);}for(const q of ['data-target','data-scan','data-all','data-none','data-preview'])$('['+q+']').disabled=hospitalBusy;$('[data-target]').disabled=hospitalBusy||Boolean(job);$('[data-pause]').disabled=!hospitalBusy;$('[data-resume]').disabled=hospitalBusy||!job||job.state==='complete';$('[data-run]').disabled=hospitalBusy||!quote||Boolean(job);};
 const guard=async fn=>{if(hospitalBusy)return;hospitalBusy=true;hospitalStop=false;render();try{if(!navigator.locks?.request)throw Error('This browser cannot provide the cross-tab upgrade lock.');await navigator.locks.request('mcms-hospital-upgrades',{ifAvailable:true},async lock=>{if(!lock)throw Error('Hospital upgrades are open for work in another tab.');await fn();});}catch(e){say(e.message);}finally{hospitalBusy=false;render();}};
 const identity=async()=>{const a=await hospitalBridge.account();if(accountId&&accountId!==String(a.user_id))throw Error('Game account changed. Close and reopen this tool.');accountId=String(a.user_id);return a;};
 $('[data-close]').onclick=()=>d.close();d.addEventListener('cancel',()=>{});
 $('[data-target]').onchange=()=>{rows=hospitalPlan(rows.map(r=>({id:r.id,caption:r.name,level:r.level,typeId:'4'})),$('[data-target]').value);quote=null;render();};
 $('[data-all]').onclick=()=>{rows.forEach(r=>r.selected=r.steps>0);quote=null;render();};$('[data-none]').onclick=()=>{rows.forEach(r=>r.selected=false);quote=null;render();};
 $('[data-scan]').onclick=()=>guard(async()=>{await identity();const saved=localStorage.getItem(key());if(saved){const old=JSON.parse(saved);if(old.items?.some(i=>i.intent))throw Error('An earlier purchase is uncertain. Use Review & resume to verify it before making a new plan.');}if(job&&job.state!=='complete'&&!window.confirm('Replace the paused plan with a fresh hospital scan?'))return;job=null;quote=null;say('Loading owned hospitals…');rows=hospitalPlan(await hospitalBridge.list(),$('[data-target]').value);say(`${rows.length} hospitals loaded; ${rows.filter(r=>r.steps>0).length} below target.`);});
 $('[data-preview]').onclick=()=>guard(async()=>{await identity();if(job)throw Error('Load hospitals to create a new plan.');quote=null;const selected=rows.filter(r=>r.selected&&r.steps>0);if(!selected.length)throw Error('Select at least one hospital below target.');const context=hospitalBridge.scanContext?await hospitalBridge.scanContext(accountId):null;let total=0,levels=0;for(const [index,r]of selected.entries()){if(hospitalStop)throw Error('Cost scan paused.');say(`Checking prices ${index+1}/${selected.length}: ${r.name}`);const fresh=await hospitalBridge.inspect(r.id,accountId,r.target,context);r.level=fresh.record.level;r.steps=Math.max(0,r.target-r.level);if(!r.steps){r.state='already-ready';continue;}if(!fresh.operation)throw Error(`${r.name}: no native Credit level upgrade is available.`);r.quotedPrice=fresh.operation.priceCredits;r.unitPrice=fresh.operation.targetLevel?Math.ceil(r.quotedPrice/r.steps):r.quotedPrice;if(!Number.isSafeInteger(r.unitPrice)||r.unitPrice<=0)throw Error('Invalid native price.');total+=fresh.operation.targetLevel?r.quotedPrice:r.steps*r.unitPrice;levels+=r.steps;r.state=`${(fresh.operation.targetLevel?r.quotedPrice:r.steps*r.unitPrice).toLocaleString()} CR to target`;}quote={total,levels,items:selected.filter(r=>r.steps>0).map(r=>({...r})),target:hospitalTarget($('[data-target]').value)};say(`${quote.items.length} hospitals · ${levels} level upgrades · Estimated ${total.toLocaleString()} Credits. Higher live prices will pause the run.`);});
 const execute=async()=>{await identity();await hospitalBridge.exclusive(async()=>{await runHospitalUpgrades(job,hospitalBridge,{save,stopped:()=>hospitalStop});});say(`${job.state}: ${job.items.filter(i=>i.level>=i.target).length}/${job.items.length} hospitals at target · ${job.items.reduce((n,i)=>n+i.purchased,0)} verified upgrades · ${job.spent.toLocaleString()} Credits recorded.`);};
 $('[data-run]').onclick=()=>guard(async()=>{if(!quote?.items.length)throw Error('Preview selected costs first.');const balance=hospitalCreditBalance(await identity());if(!window.confirm(`Upgrade ${quote.items.length} selected hospitals to level ${quote.target}?\n${quote.levels} level upgrades\nYour available balance: ${balance.toLocaleString()} Credits.\nUpgrade plan spending limit: ${quote.total.toLocaleString()} Credits.\nHigher prices pause the run. Sharing and tax are unchanged.`))return;job={schema:1,account:accountId,target:quote.target,ceiling:quote.total,spent:0,state:'ready',items:quote.items.map(i=>({...i,state:'pending'}))};await save(job);quote=null;await execute();});
 $('[data-pause]').onclick=()=>{hospitalStop=true;say('Pausing after the current request is verified…');};
 $('[data-resume]').onclick=()=>guard(async()=>{const balance=hospitalCreditBalance(await identity());const saved=localStorage.getItem(key());if(!saved)throw Error('No saved upgrade plan.');job=JSON.parse(saved);if(!window.confirm(`Resume hospital upgrades to level ${job.target}?\nYour available balance: ${balance.toLocaleString()} Credits.\nRemaining upgrade-plan limit: ${(job.ceiling-job.spent).toLocaleString()} Credits.\nUncertain purchases are verified before continuing.`))return;await execute();});
 guard(async()=>{await identity();const saved=localStorage.getItem(key());if(saved){job=JSON.parse(saved);$('[data-target]').value=String(job.target);say(`Saved ${job.state} plan loaded. Review & resume to continue.`);}});
}
