import test from 'node:test';import assert from 'node:assert/strict';import {createImageBridge} from './images.mjs';
test('picker groups equal pixels across URLs and bounds simultaneous downloads',async()=>{
 const records=Array.from({length:12},(_,i)=>({id:String(i),caption:`Station ${i}`,hasCustomIcon:true,customIconUrl:`https://example.com/${i%8}.png`}));let active=0,max=0,calls=0;
 const bridge=createImageBridge({list:async()=>records,image:async url=>{calls++;max=Math.max(max,++active);await new Promise(r=>setTimeout(r,2));active--;if(url.endsWith('/7.png'))throw Error('Unavailable');return {width:32,height:32,pixelDigest:Number(url.match(/(\d+)\.png/)[1])%2?'odd':'even'};}});
 const result=await bridge.sources();assert.equal(calls,8);assert.equal(max,4);assert.equal(result.icons.length,2);assert.equal(result.unavailable,1);assert.equal(result.icons.reduce((n,i)=>n+i.count,0),11);
});
function fixture(){const source={id:'1',caption:'Source',hasCustomIcon:true,customIconUrl:'https://example.com/icon.png'},target={id:'2',caption:'New home',typeId:22,longitude:-3.19,latitude:55.95,dispatchId:'4',small:false};let digest='a';const calls=[];const deps={list:async()=>[source],building:async id=>String(id)==='1'?source:target,image:async()=>({pixelDigest:digest,width:32,height:32}),apply:async(...args)=>calls.push(args)};return {deps,target,calls,setDigest:d=>digest=d,item:{buildingId:'2',name:'New home',point:[-3.19,55.95]}};}
test('copies verified source through existing copier with precise target identity',async()=>{const f=fixture(),bridge=createImageBridge(f.deps),imageSource=await bridge.prepare('1');await bridge.copy(f.item,{imageSource});assert.equal(f.calls.length,1);assert.equal(f.calls[0][0].buildingId,'2');assert.equal(f.calls[0][0].dispatchId,'4');assert.equal(f.calls[0][2].pixelDigest,'a');});
test('changed source after reload and wrong target both stop image changes',async()=>{const f=fixture(),first=createImageBridge(f.deps),imageSource=await first.prepare('1');f.setDigest('b');await assert.rejects(createImageBridge(f.deps).copy(f.item,{imageSource}),/source image has changed/);f.setDigest('a');f.target.typeId=7;await assert.rejects(first.copy(f.item,{imageSource}),/identity changed/);assert.equal(f.calls.length,0);});
