import {dispatchAreaCenter,rankedDispatchCentres,dispatchAcknowledgement} from './dispatch.mjs';
import {LAND_GEOMETRY} from './land-data.mjs';
import {isDryLand} from './land.mjs';
import {planAsync,circle,contains,distanceMiles,SPACING_MILES} from './planner.mjs';
import {VEHICLES} from './catalogue.mjs';
import {nativeAdapter} from './native.mjs';
import {runQueue} from './queue.mjs';
export function mount(grid){
 if(grid.querySelector('[data-hr-builder]'))return;
 const launcher=document.createElement('button');launcher.type='button';launcher.dataset.hrBuilder='true';launcher.className='mcms-small-btn';
 for(const [tag,text]of [['strong','Home Response Builder'],['span','Plan locations around existing buildings, then build and equip them.'],['small','New']]){const e=document.createElement(tag);e.textContent=text;launcher.append(e);}grid.append(launcher);
 launcher.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();open();});
}
let dialog,teardown=()=>{},imageBridge;
export function configureImages(bridge){imageBridge=bridge;}
export function destroy(){teardown();}
function open(){
 if(dialog?.isConnected){dialog.showModal();return;}
 dialog=document.createElement('dialog');dialog.className='tkb-hr';
 dialog.innerHTML=`<style>
 .tkb-hr .hr-dispatch-label{background:#181c20;color:#fff;border:1px solid #edbb58;box-shadow:0 1px 4px #0008;font:12px/1.3 system-ui}.tkb-hr .hr-spacing-toggle{flex-direction:row;align-items:center;gap:8px;margin:8px 0}.tkb-hr .hr-spacing-toggle input{width:18px;height:18px;min-height:18px;padding:0;margin:0;flex:none;appearance:auto}.tkb-hr .hr-icon-grid{display:flex;flex-wrap:wrap;gap:8px;max-height:230px;overflow:auto;margin:8px 0}.tkb-hr .hr-icon-grid button{width:90px;min-height:82px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;font-size:12px}.tkb-hr .hr-icon-grid img{width:44px;height:44px;object-fit:contain}.tkb-hr .hr-icon-grid [aria-pressed="true"]{border:2px solid #ed2727;background:#39171a}.tkb-hr [data-icon-status]{display:block}
 .tkb-hr{background:#101416;color:#eee;border:1px solid #50575b;border-top:3px solid #ed2727;border-radius:8px;padding:18px;width:min(1100px,94vw);max-height:90dvh;box-sizing:border-box;font:14px/1.5 system-ui}.tkb-hr::backdrop{background:#0009}.tkb-hr h2{margin:0}.tkb-hr header{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.tkb-hr button,.tkb-hr input,.tkb-hr select{background:#202629;color:#fff;border:1px solid #566169;border-radius:4px;min-height:40px;padding:7px;font:inherit;max-width:100%;box-sizing:border-box}.tkb-hr button{cursor:pointer}.tkb-hr button:disabled{opacity:.5;cursor:default}.tkb-hr :focus-visible{outline:2px solid #ed2727;outline-offset:2px}.tkb-hr .fields{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}.tkb-hr label{display:flex;flex-direction:column;gap:4px}.tkb-hr .hr-map{height:350px;background:#151c20;border:1px solid #465057;border-radius:5px}.tkb-hr .primary{background:#8b181c}.tkb-hr p{margin:8px 0}.tkb-hr output{display:block;padding:10px;background:#1e282d;border-left:3px solid #ed2727}.tkb-hr .results{max-height:160px;overflow:auto}.tkb-hr select,.tkb-hr input{color:#f4f5f6!important;-webkit-text-fill-color:#f4f5f6!important;opacity:1}.tkb-hr output{color:#f4f5f6!important}.tkb-hr [hidden]{display:none!important}.tkb-hr small{color:#bbc3c8}.tkb-hr .leaflet-popup-content{color:#111}.tkb-hr .hr-proposed{background:#ed2727;border:2px solid white;border-radius:50%}.tkb-hr .hr-existing{background:#758da2;border:2px solid white;border-radius:50%}
 </style><header><h2>Home Response Builder</h2><button data-close type="button">Close</button></header>
 <p>Choose an area, preview locations and costs, then review your build plan. Distances are straight-line miles.</p>
 <fieldset data-controls><legend>Area & configuration</legend><div class="fields"><label>City shortlist<select data-cities><option value="">Choose a city</option></select></label><label>UK city or town<input data-city placeholder="Edinburgh" maxlength="100"></label><button data-search type="button">Find area</button><label>Search results<select data-places><option value="">Choose a result</option></select></label></div>
 <div class="fields"><label>Area selection<select data-mode><option value="boundary">City boundary</option><option value="radius">Point and radius</option><option value="draw">Draw boundary</option><option value="exclude">Draw exclusion</option></select></label><label>Radius (miles)<input data-radius type="number" min="1" max="100" value="5" disabled></label><button data-finish type="button">Finish drawing</button><button data-clear type="button">Clear exclusions</button></div>
 <p><small>For a radius, click its centre on the map. To draw, click the boundary corners then Finish drawing. Mapped sea and lakes are excluded automatically. Check small waterways and road access before building.</small></p>
 <p data-area-hint>City boundary uses the selected mapped boundary; radius applies only in Point and radius mode.</p><label class="hr-spacing-toggle"><input data-circles type="checkbox">Show spacing around existing and proposed buildings</label><details data-diagnostics hidden><summary>Why this many locations?</summary><p data-breakdown></p></details><output data-status role="status">Choose an area to begin.</output><div data-map class="hr-map"></div><p>Grey: existing Home Responses · Red: proposed locations. Drag a proposed marker to move it; click it to remove it.</p>
 <div class="fields"><label>Minimum spacing (miles)<select data-spacing></select></label><label>Vehicle<select data-vehicle></select></label><label>Maximum new buildings<input data-limit type="number" min="1" max="1000" value="20"></label><label>Name prefix<input data-name maxlength="60" value="Home Response"></label><label>Dispatch centre<select data-dispatch><option value="">Unassigned</option></select><small data-dispatch-status role="status">Loading dispatch centres…</small></label><label hidden>Copy building image from<select data-image><option value="">Keep default image</option></select></label></div><section aria-label="Building icon"><strong>Building icon</strong><label>Scan building type<select data-icon-type><option value="">All building types</option></select></label><button data-load-icons type="button">Scan / refresh selected type</button><small data-icon-status role="status">Keep default, or load your unique building icons.</small><div data-icon-grid class="hr-icon-grid"></div></section><p data-training></p><button data-preview type="button" class="primary">Refresh buildings & preview</button></fieldset>
 <p><small>The building limit is a maximum, not a target. Available land and spacing determine the number proposed.</small></p><div class="fields"><button data-build type="button" class="primary" disabled>Review & build</button><button data-stop type="button" disabled>Pause after current request</button><button data-resume type="button" disabled>Review & resume</button></div><div data-results class="results"></div>`;
 document.body.append(dialog);dialog.showModal();
 const rootDialog=dialog;const $=s=>rootDialog.querySelector(s),api=nativeAdapter(window);let geometry=null,cityBoundary=null,radiusCenter=null,exclusions=[],drawn=[],records=[],proposal=null,job=null,busy=false,stop=false,accountId='',map=null,layers=null,places=[],searchAt=0,catalogueRequest=0,catalogueLoaded=false,dispatchArea=null,manualDispatch=false;
 teardown=()=>{stop=true;map?.remove();rootDialog.remove();};
 api.copyImage=async(item,job)=>{if(!imageBridge)throw Error('Building image copier is unavailable.');await imageBridge.copy(item,job);};
 const say=t=>$('[data-status]').textContent=t;
 const progressRows=new Map();let reportFrame=0,reportedJob;
 const report=()=>{if(reportFrame)return;reportFrame=window.requestAnimationFrame(()=>{reportFrame=0;if(!rootDialog.isConnected||!job)return;const root=$('[data-results]');if(reportedJob!==job||progressRows.size!==job.items.length){root.replaceChildren();progressRows.clear();reportedJob=job;}for(const i of job.items){let row=progressRows.get(i);if(!row){row=document.createElement('p');progressRows.set(i,row);root.append(row);}const text=`${i.name}: ${i.state}${i.imageDone?' — image copied':''}${i.detail?' — '+i.detail:''}${i.error?' — '+i.error:''}`;if(row.textContent!==text)row.textContent=text;}});};

 const key=()=>`mcms_home_response_job_${accountId}`;
 const save=async j=>{const text=JSON.stringify(j);window.localStorage.setItem(key(),text);if(window.localStorage.getItem(key())!==text)throw Error('Could not save the build checkpoint.');report();};
 const invalidate=()=>{proposal=null;$('[data-build]').disabled=true;$('[data-diagnostics]').hidden=true;updateDispatch();render();say(geometry?'Area or settings changed. Refresh buildings & preview to update locations.':'Choose an area to begin.');};
 const selectedVehicle=()=>VEHICLES.find(v=>v.id===Number($('[data-vehicle]').value));
 for(const s of SPACING_MILES){const o=new Option(String(s),String(s));$('[data-spacing]').add(o);}$('[data-spacing]').value='3';
 for(const v of VEHICLES)$('[data-vehicle]').add(new Option(`${v.name} · ${v.credits.toLocaleString()} CR`,String(v.id)));
 function training(){const v=selectedVehicle();$('[data-training]').textContent=v.training?`Requires ${v.training}. Purchased vehicles will still need suitable trained crew.`:'The builder purchases vehicles; check crew readiness afterwards.';}training();
 for(const city of ['Aberdeen','Armagh','Bangor, Northern Ireland','Bath','Belfast','Birmingham','Bradford','Brighton and Hove','Bristol','Cambridge','Canterbury','Cardiff','Carlisle','Chelmsford','Chester','Chichester','Colchester','Coventry','Derby','Derry','Doncaster','Dundee','Dunfermline','Durham','Edinburgh','Ely','Exeter','Glasgow','Gloucester','Hereford','Inverness','Kingston upon Hull','Lancaster','Leeds','Leicester','Lichfield','Lincoln','Lisburn','Liverpool','London','Manchester','Milton Keynes','Newcastle upon Tyne','Newport','Newry','Norwich','Nottingham','Oxford','Perth','Peterborough','Plymouth','Portsmouth','Preston','Ripon','Salford','Salisbury','Sheffield','Southampton','Southend-on-Sea','St Albans','St Andrews','St Davids','Stirling','Stoke-on-Trent','Sunderland','Swansea','Truro','Wakefield','Wells','Westminster','Winchester','Wolverhampton','Worcester','Wrexham','York'])$('[data-cities]').add(new Option(city,city));
 $('[data-cities]').onchange=()=>{if($('[data-cities]').value){$('[data-city]').value=$('[data-cities]').value;$('[data-search]').click();}};
 let loadingIcons=false,iconView=0;
 function updateIconTypes(){const select=$('[data-icon-type]'),previous=select.value;const types=[...new Set(records.map(b=>String(b.building_type)))].sort((a,b)=>(imageBridge?.typeName?.(a)||a).localeCompare(imageBridge?.typeName?.(b)||b));select.replaceChildren(new Option('All building types',''),...types.map(id=>new Option(imageBridge?.typeName?.(id)||`Building type ${id}`,id)));select.value=types.includes(previous)?previous:'';}
 function installIcons(icons){const select=$('[data-image]'),previous=select.value;select.replaceChildren(new Option('Keep default image',''));icons.forEach(i=>select.add(new Option(i.caption,String(i.id))));select.value=previous;if(select.selectedIndex<0)select.value='';showIcons(icons);}
 async function restoreIcons(){const view=++iconView,typeId=$('[data-icon-type]').value||null;const data=await imageBridge?.saved?.({typeId});if(!rootDialog.isConnected||view!==iconView)return;installIcons(data?.icons||[]);$('[data-icon-status]').textContent=data?`${data.icons.length} saved icons · last scanned ${new Date(data.savedAt).toLocaleString()}. Refresh to include changed images.`:'No saved icons for this type. Scan once to remember them in this browser.';}
 $('[data-icon-type]').onchange=()=>{if(!loadingIcons)void restoreIcons();};

 function showIcons(icons=[]){const grid=$('[data-icon-grid]'),selected=$('[data-image]').value;grid.replaceChildren();for(const icon of [{id:'',caption:'Default',count:0},...icons]){const button=document.createElement('button');button.type='button';button.dataset.iconId=String(icon.id);button.setAttribute('aria-pressed',String(String(icon.id)===selected));button.setAttribute('aria-label',icon.id?`Use icon from ${icon.caption}, used by ${icon.count} buildings`:'Keep default icon');if(icon.customIconUrl){const img=document.createElement('img');img.src=icon.customIconUrl;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';button.append(img);}const label=document.createElement('span');label.textContent=icon.id?`${icon.count} building${icon.count===1?'':'s'}`:'Default';button.append(label);button.title=icon.caption;button.onclick=()=>{if(busy)return;$('[data-image]').value=String(icon.id);for(const b of grid.children)b.setAttribute('aria-pressed',String(b===button));};grid.append(button);}}
 showIcons();
 $('[data-load-icons]').onclick=async()=>{if(loadingIcons||busy)return;if(!imageBridge){$('[data-icon-status]').textContent='Image copier is unavailable.';return;}loadingIcons=true;++iconView;$('[data-icon-type]').disabled=true;$('[data-load-icons]').disabled=true;try{const result=await imageBridge.sources({typeId:$('[data-icon-type]').value||null,onProgress:p=>{$('[data-icon-status]').textContent=`Checking unique images… ${p.done}/${p.total}`;}});if(!rootDialog.isConnected)return;installIcons(result.icons);$('[data-icon-status]').textContent=`${result.icons.length} unique icons${result.unavailable?` · ${result.unavailable} building images unavailable`:''}. ${result.persisted?'Saved for next time.':result.persisted===false?'Browser storage is full or unavailable; icons were not saved.':''}`;}catch(e){$('[data-icon-status]').textContent=e.message;}finally{loadingIcons=false;$('[data-icon-type]').disabled=false;$('[data-load-icons]').disabled=false;}};
 const L=window.L;
 if(L?.map){map=L.map($('[data-map]')).setView([55.95,-3.19],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);layers=L.layerGroup().addTo(map);setTimeout(()=>map.invalidateSize(),0);
 map.on('click',e=>{if(busy)return;const p=[e.latlng.lng,e.latlng.lat],mode=$('[data-mode]').value;if(mode==='radius'){try{geometry=circle(p,Number($('[data-radius]').value));radiusCenter=p;invalidate();}catch(e){say(e.message);}}else if(['draw','exclude'].includes(mode)){drawn.push(p);L.circleMarker(e.latlng,{radius:4,color:'#ed2727'}).addTo(layers);}});
 }else{say('The game map library is not ready. Close and reopen this tool after the game finishes loading.');$('[data-preview]').disabled=true;}
 function dispatchList(){return rankedDispatchCentres(records,dispatchAreaCenter(geometry));}
 function updateDispatch(){if(dispatchArea!==geometry){dispatchArea=geometry;manualDispatch=false;}const select=$('[data-dispatch]'),previous=select.value,list=dispatchList();select.replaceChildren(...list.map((b,i)=>new Option(`${b.name}${b.miles===null?'':` · ${b.miles.toFixed(1)} mi${i===0?' · nearest':''}`}`,b.id)),new Option('Unassigned',''));select.value=!manualDispatch&&geometry&&list[0]?.miles!==null&&list.length?list[0].id:list.some(b=>b.id===previous)?previous:'';if(catalogueLoaded)$('[data-dispatch-status]').textContent=list.length?`${list.length} centres · ${geometry?'nearest first, straight-line miles from area centre':'choose an area to sort by distance'}. Gold markers show their names.`:'No dispatch centres found.';}
 async function loadCatalogue(){const request=++catalogueRequest;const next=await api.buildings();if(!rootDialog.isConnected||request!==catalogueRequest)return;records=next;catalogueLoaded=true;updateIconTypes();updateDispatch();render();}
 function render(){if(!map)return;layers.clearLayers();if(geometry)L.geoJSON(geometry,{style:{color:'#ed2727',weight:2,fillOpacity:.05}}).addTo(layers);for(const g of exclusions)L.geoJSON(g,{style:{color:'#e8b15b',weight:2,fillOpacity:.2}}).addTo(layers);
 for(const b of dispatchList()){if(!b.point)continue;const label=document.createElement('span');label.textContent=b.name;L.circleMarker([b.point[1],b.point[0]],{radius:8,color:'#edbb58',weight:2,fillColor:'#202629',fillOpacity:1}).addTo(layers).bindTooltip(label,{permanent:true,direction:'top',className:'hr-dispatch-label'}).on('click',()=>{if(!busy){manualDispatch=true;$('[data-dispatch]').value=b.id;}});}
 for(const b of records.filter(b=>Number(b.building_type)===22)){L.circleMarker([b.latitude,b.longitude],{radius:4,color:'#9ab1c4'}).addTo(layers);if($('[data-circles]').checked)L.circle([b.latitude,b.longitude],{radius:Number($('[data-spacing]').value)*1609.344,color:'#9ab1c4',weight:1,fillOpacity:.07,interactive:false}).addTo(layers);}
 for(const p of proposal?.sites||[]){if($('[data-circles]').checked)L.circle([p[1],p[0]],{radius:Number($('[data-spacing]').value)*1609.344,color:'#ed2727',weight:1,fillOpacity:.035,interactive:false}).addTo(layers);const marker=L.marker([p[1],p[0]],{draggable:true,icon:L.divIcon({className:'hr-proposed',iconSize:[12,12]})}).addTo(layers);marker.on('dragend',()=>{if(busy){marker.setLatLng([p[1],p[0]]);return;}const ll=marker.getLatLng(),q=[ll.lng,ll.lat],spacing=Number($('[data-spacing]').value);const others=[...records.filter(b=>Number(b.building_type)===22).map(b=>[b.longitude,b.latitude]),...proposal.sites.filter(x=>x!==p)];if(!isDryLand(q)||!contains(geometry,q)||exclusions.some(g=>contains(g,q))||others.some(x=>distanceMiles(x,q)<spacing)){marker.setLatLng([p[1],p[0]]);say('That position is on water, near an uncertain shoreline, outside the area or too close to another location.');return;}p.splice(0,2,...q);render();summary();});marker.on('click',()=>{if(busy)return;proposal.sites=proposal.sites.filter(x=>x!==p);render();summary();});}
 }
 function summary(){if(!proposal)return;const count=proposal.sites.length,total=count*(10000+selectedVehicle().credits),existing=records.filter(b=>Number(b.building_type)===22),inside=existing.filter(b=>contains(geometry,[b.longitude,b.latitude])).length;$('[data-build]').disabled=!count;say(`${count} proposed at ${proposal.spacingMiles}-mile minimum spacing · estimated ${total.toLocaleString()} Credits including vehicles · ${inside} existing Home Responses inside this area (${existing.length} checked across your account).${proposal.limitReached?` The preview reached your maximum of ${proposal.count} buildings. Locations are sampled across the area; increase Maximum new buildings (up to 1000) for more.`:''} Review roads, exclusions and crew requirements.`);$('[data-diagnostics]').hidden=false;$('[data-breakdown]').textContent=`${proposal.gapAdded} additional locations found by the gap search. Sampled positions excluded: ${proposal.existingBlocked} too close to existing buildings; ${proposal.proposedBlocked} too close to proposed locations; ${proposal.waterExcluded} water/shoreline; ${proposal.excludedPoints} in drawn exclusions. These are search samples, not missing buildings. Spacing applies to both existing and new buildings. Tripling spacing typically leaves room for roughly one ninth as many buildings over a large open area; boundaries and existing buildings change the actual count. Existing buildings outside the boundary can also exclude nearby positions. Enable spacing circles to see their reach. This is a geometric proposal, not a guaranteed maximum.`;}
 const safe=fn=>async()=>{try{await fn();}catch(e){say(e.message);}};
 $('[data-close]').onclick=()=>{if(busy){say('Pause the build queue before closing.');return;}map?.remove();dialog.remove();dialog=null;};dialog.addEventListener('cancel',e=>{e.preventDefault();$('[data-close]').click();});
 $('[data-controls]').addEventListener('change',e=>{if(e.target.matches('[data-dispatch]'))manualDispatch=true;if(e.target.matches('[data-mode],[data-places],[data-cities],[data-circles],[data-radius],[data-icon-type]'))return;if(e.target.matches('[data-image],[data-name],[data-dispatch],[data-vehicle]')){training();summary();return;}invalidate();training();});
 $('[data-circles]').onchange=render;
 function areaControls(){const mode=$('[data-mode]').value;$('[data-radius]').disabled=mode!=='radius';$('[data-finish]').disabled=!['draw','exclude'].includes(mode);$('[data-area-hint]').textContent=mode==='boundary'?'City boundary uses the selected mapped boundary. Radius does not apply.':mode==='radius'?'Click a centre on the map or select a search result. Radius controls the area size.':mode==='draw'?'Click boundary corners, then Finish drawing.':'Click exclusion corners, then Finish drawing. Your main area stays selected.';}
 $('[data-mode]').onchange=safe(()=>{drawn=[];areaControls();invalidate();const mode=$('[data-mode]').value;if(mode==='boundary')geometry=cityBoundary;else if(mode==='radius')geometry=radiusCenter?circle(radiusCenter,Number($('[data-radius]').value)):null;else if(mode==='draw')geometry=null;areaControls();invalidate();});
 $('[data-radius]').onchange=safe(()=>{if($('[data-mode]').value!=='radius')return;geometry=null;invalidate();if(radiusCenter)geometry=circle(radiusCenter,Number($('[data-radius]').value));invalidate();});
 areaControls();
 $('[data-finish]').onclick=safe(()=>{if(drawn.length<3)throw Error('Click at least three boundary corners.');const g={type:'Polygon',coordinates:[[...drawn,[...drawn[0]]]]};if($('[data-mode]').value==='exclude')exclusions.push(g);else geometry=g;drawn=[];invalidate();render();});
 $('[data-clear]').onclick=()=>{exclusions=[];drawn=[];invalidate();render();};
 $('[data-search]').onclick=safe(async()=>{const q=$('[data-city]').value.trim();if(!q)throw Error('Enter a city or town.');if(Date.now()-searchAt<1500)throw Error('Please wait a moment before searching again.');searchAt=Date.now();$('[data-search]').disabled=true;say('Finding UK area boundaries…');try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=gb&polygon_geojson=1&limit=5&q='+encodeURIComponent(q),{credentials:'omit',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Area search unavailable. Use a point and radius or draw your boundary.');places=await r.json();$('[data-places]').replaceChildren(new Option('Choose a result',''));places.forEach((p,i)=>$('[data-places]').add(new Option(p.display_name,String(i))));say('Choose a result. Boundary data: © OpenStreetMap contributors.');}finally{$('[data-search]').disabled=false;}});
 $('[data-places]').onchange=safe(()=>{if($('[data-places]').value==='')return;const p=places[Number($('[data-places]').value)];if(!p)return;radiusCenter=[Number(p.lon),Number(p.lat)];cityBoundary=['Polygon','MultiPolygon'].includes(p.geojson?.type)?p.geojson:null;drawn=[];geometry=null;invalidate();$('[data-mode]').value='boundary';geometry=cityBoundary;areaControls();invalidate();if(map&&geometry)map.fitBounds(L.geoJSON(geometry).getBounds());if(!cityBoundary)say('This result has no mapped boundary. Choose another result, or explicitly select Point and radius or Draw boundary.');});
 $('[data-preview]').onclick=safe(async()=>{invalidate();if(!geometry)throw Error('Choose an area first.');$('[data-preview]').disabled=true;busy=true;$('[data-controls]').disabled=true;try{say('Checking your existing buildings…');const a=await api.account();accountId=String(a.user_id);await loadCatalogue();
 proposal=await planAsync({geometry,landGeometry:LAND_GEOMETRY,excluded:exclusions,spacingMiles:Number($('[data-spacing]').value),existing:records.filter(b=>Number(b.building_type)===22).map(b=>[b.longitude,b.latitude]),maxBuildings:Number($('[data-limit]').value)},{cancelled:()=>!rootDialog.isConnected,onProgress:p=>say(`Planning locations… ${p.count} found`)});
 render();summary();const old=window.localStorage.getItem(key());if(old){const parsed=JSON.parse(old);if(parsed.account===accountId&&parsed.state!=='complete'){job=parsed;$('[data-resume]').disabled=false;report();}}}finally{busy=false;$('[data-controls]').disabled=false;$('[data-preview]').disabled=false;}});
 $('[data-stop]').onclick=()=>{stop=true;say('Pausing after the current request is checked.');};
 async function execute(){if(!navigator.locks?.request)throw Error('This browser cannot lock the build queue across tabs. Use a browser supporting Web Locks for construction.');
 await navigator.locks.request('mcms-home-response-build',{ifAvailable:true},async lock=>{if(!lock)throw Error('Another tab is running Home Response Builder.');const stored=window.localStorage.getItem(key());if(stored){const fresh=JSON.parse(stored);if(fresh.account!==accountId)throw Error('Saved account mismatch.');if(fresh.id===job.id)job=fresh;else if(fresh.state!=='complete')throw Error('Another saved build plan must be resolved first.');}await api.checkAccount(job.account);const count=job.items.filter(i=>!['complete','skipped'].includes(i.state)).length;const assignment=dispatchAcknowledgement(job,await api.buildings());if(!window.confirm(`${assignment}\n\nBuild/equip up to ${count} locations with ${job.vehicle.name}? Estimated original plan cost: ${(job.items.length*(10000+job.vehicle.credits)).toLocaleString()} Credits.${job.imageSource?' Copy image from '+job.imageSource.name+'.':''} Already recorded spending: ${job.spent.toLocaleString()} Credits. This makes real game changes. Water locations in older saved plans will be skipped before construction. Crew training is not included.`)){if(job.state==='ready')job=null;return;}busy=true;stop=false;$('[data-controls]').disabled=true;$('[data-build]').disabled=true;$('[data-resume]').disabled=true;$('[data-stop]').disabled=false;
 try{await runQueue(job,api,{save,stopped:()=>stop});say(job.state==='complete'?'Build plan completed. Check vehicle crew readiness.':'Paused. Completed work is saved.');}finally{busy=false;$('[data-controls]').disabled=false;$('[data-stop]').disabled=true;$('[data-resume]').disabled=job.state==='complete';report();}});}
 $('[data-build]').onclick=safe(async()=>{if(!proposal?.sites.length)throw Error('Generate a preview first.');if(job&&job.state!=='complete')throw Error('Finish or inspect the saved plan before starting another.');const name=$('[data-name]').value.trim();if(!name)throw Error('Enter a name prefix.');const imageSource=$('[data-image]').value?await imageBridge.prepare($('[data-image]').value):null;const id=Date.now().toString(36);job={account:accountId,id,vehicle:selectedVehicle(),spacingMiles:Number($('[data-spacing]').value),dispatchId:$('[data-dispatch]').value,areaCenter:dispatchAreaCenter(geometry),imageSource,spent:0,state:'ready',items:proposal.sites.map((point,i)=>({point:[...point],name:`${name} ${i+1} [${id}]`,state:'ready'}))};await execute();});
 $('[data-resume]').onclick=safe(execute);
 void (async()=>{const view=iconView,last=await imageBridge?.lastType?.();if(!rootDialog.isConnected||view!==iconView)return;if(last!==null&&last!==undefined){const select=$('[data-icon-type]');if(![...select.options].some(o=>o.value===String(last)))select.add(new Option(imageBridge?.typeName?.(last)||`Building type ${last}`,String(last)));select.value=String(last);}await restoreIcons();})();
 void loadCatalogue().catch(e=>{if(rootDialog.isConnected&&catalogueRequest===1)$('[data-dispatch-status]').textContent=`Dispatch centres could not load: ${e.message} Use Refresh buildings & preview to retry.`;});
 // Restore the account-scoped checkpoint on opening; no new area selection is needed.
 void (async()=>{try{const a=await api.account();if(!rootDialog.isConnected||busy)return;accountId=String(a.user_id);const stored=window.localStorage.getItem(key());if(!stored)return;const saved=JSON.parse(stored);if(saved.account!==accountId||!Array.isArray(saved.items)||saved.state==='complete')return;job=saved;$('[data-resume]').disabled=false;report();say('Saved build plan found. Review & resume checks any interrupted purchase against the game before continuing.');}catch(e){if(rootDialog.isConnected)say(e.message);}})();

}
