import {plan,circle,contains,distanceMiles,SPACING_MILES} from './planner.mjs';
import {VEHICLES} from './catalogue.mjs';
import {nativeAdapter} from './native.mjs';
import {runQueue} from './queue.mjs';
export function mount(grid){
 if(grid.querySelector('[data-hr-builder]'))return;
 const launcher=document.createElement('button');launcher.type='button';launcher.dataset.hrBuilder='true';launcher.className='mcms-small-btn';
 for(const [tag,text]of [['strong','Home Response Builder'],['span','Plan locations around existing buildings, then build and equip them.'],['small','New']]){const e=document.createElement(tag);e.textContent=text;launcher.append(e);}grid.append(launcher);
 launcher.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();open();});
}
let dialog,teardown=()=>{};
export function destroy(){teardown();}
function open(){
 if(dialog?.isConnected){dialog.showModal();return;}
 dialog=document.createElement('dialog');dialog.className='tkb-hr';
 dialog.innerHTML=`<style>
 .tkb-hr{background:#101416;color:#eee;border:1px solid #50575b;border-top:3px solid #ed2727;border-radius:8px;padding:18px;width:min(1100px,94vw);max-height:90dvh;box-sizing:border-box;font:14px/1.5 system-ui}.tkb-hr::backdrop{background:#0009}.tkb-hr h2{margin:0}.tkb-hr header{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.tkb-hr button,.tkb-hr input,.tkb-hr select{background:#202629;color:#fff;border:1px solid #566169;border-radius:4px;min-height:40px;padding:7px;font:inherit;max-width:100%;box-sizing:border-box}.tkb-hr button{cursor:pointer}.tkb-hr button:disabled{opacity:.5;cursor:default}.tkb-hr :focus-visible{outline:2px solid #ed2727;outline-offset:2px}.tkb-hr .fields{display:flex;flex-wrap:wrap;gap:10px;margin:12px 0}.tkb-hr label{display:flex;flex-direction:column;gap:4px}.tkb-hr .hr-map{height:350px;background:#151c20;border:1px solid #465057;border-radius:5px}.tkb-hr .primary{background:#8b181c}.tkb-hr p{margin:8px 0}.tkb-hr output{display:block;padding:10px;background:#1e282d;border-left:3px solid #ed2727}.tkb-hr .results{max-height:160px;overflow:auto}.tkb-hr select,.tkb-hr input{color:#f4f5f6!important;-webkit-text-fill-color:#f4f5f6!important;opacity:1}.tkb-hr output{color:#f4f5f6!important}.tkb-hr [hidden]{display:none!important}.tkb-hr small{color:#bbc3c8}.tkb-hr .leaflet-popup-content{color:#111}.tkb-hr .hr-proposed{background:#ed2727;border:2px solid white;border-radius:50%}.tkb-hr .hr-existing{background:#758da2;border:2px solid white;border-radius:50%}
 </style><header><h2>Home Response Builder</h2><button data-close type="button">Close</button></header>
 <p>Choose an area, preview locations and costs, then review your build plan. Distances are straight-line miles.</p>
 <fieldset data-controls><legend>Area & configuration</legend><div class="fields"><label>UK city or town<input data-city placeholder="Edinburgh" maxlength="100"></label><button data-search type="button">Find area</button><label>Search results<select data-places><option value="">Choose a result</option></select></label></div>
 <div class="fields"><label>Area selection<select data-mode><option value="boundary">City boundary</option><option value="radius">Point and radius</option><option value="draw">Draw boundary</option><option value="exclude">Draw exclusion</option></select></label><label>Radius (miles)<input data-radius type="number" min="1" max="100" value="5"></label><button data-finish type="button">Finish drawing</button><button data-clear type="button">Clear exclusions</button></div>
 <p><small>For a radius, click its centre on the map. To draw, click the boundary corners then Finish drawing. Review roads and water before building.</small></p>
 <div data-map class="hr-map"></div><p>Grey: existing Home Responses · Red: proposed locations. Drag a proposed marker to move it; click it to remove it.</p>
 <div class="fields"><label>Minimum spacing (miles)<select data-spacing></select></label><label>Vehicle<select data-vehicle></select></label><label>Maximum new buildings<input data-limit type="number" min="1" max="500" value="20"></label><label>Credit budget<input data-budget type="number" min="0" step="500" value="250000"></label><label>Name prefix<input data-name maxlength="60" value="Home Response"></label><label>Dispatch centre<select data-dispatch><option value="">Unassigned</option></select></label></div><p data-training></p><button data-preview type="button" class="primary">Refresh buildings & preview</button></fieldset>
 <output data-status role="status">Choose an area to begin.</output><div class="fields"><button data-build type="button" class="primary" disabled>Review & build</button><button data-stop type="button" disabled>Pause after current request</button><button data-resume type="button" disabled>Review & resume</button></div><div data-results class="results"></div>`;
 document.body.append(dialog);dialog.showModal();
 const rootDialog=dialog;const $=s=>rootDialog.querySelector(s),api=nativeAdapter(window);let geometry=null,exclusions=[],drawn=[],records=[],proposal=null,job=null,busy=false,stop=false,accountId='',map=null,layers=null,places=[],searchAt=0;
 teardown=()=>{stop=true;map?.remove();rootDialog.remove();};
 const say=t=>$('[data-status]').textContent=t;
 const report=()=>{const root=$('[data-results]');root.replaceChildren();if(!job)return;for(const i of job.items){const row=document.createElement('p');row.textContent=`${i.name}: ${i.state}${i.detail?' — '+i.detail:''}${i.error?' — '+i.error:''}`;root.append(row);}};
 const key=()=>`mcms_home_response_job_${accountId}`;
 const save=async j=>{const text=JSON.stringify(j);window.localStorage.setItem(key(),text);if(window.localStorage.getItem(key())!==text)throw Error('Could not save the build checkpoint.');report();};
 const invalidate=()=>{proposal=null;$('[data-build]').disabled=true;};
 const selectedVehicle=()=>VEHICLES.find(v=>v.id===Number($('[data-vehicle]').value));
 for(const s of SPACING_MILES){const o=new Option(String(s),String(s));$('[data-spacing]').add(o);}$('[data-spacing]').value='3';
 for(const v of VEHICLES)$('[data-vehicle]').add(new Option(`${v.name} · ${v.credits.toLocaleString()} CR`,String(v.id)));
 function training(){const v=selectedVehicle();$('[data-training]').textContent=v.training?`Requires ${v.training}. Purchased vehicles will still need suitable trained crew.`:'The builder purchases vehicles; check crew readiness afterwards.';}training();
 const L=window.L;
 if(L?.map){map=L.map($('[data-map]')).setView([55.95,-3.19],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);layers=L.layerGroup().addTo(map);setTimeout(()=>map.invalidateSize(),0);
 map.on('click',e=>{if(busy)return;const p=[e.latlng.lng,e.latlng.lat],mode=$('[data-mode]').value;if(mode==='radius'){geometry=circle(p,Number($('[data-radius]').value));invalidate();render();}else if(['draw','exclude'].includes(mode)){drawn.push(p);L.circleMarker(e.latlng,{radius:4,color:'#ed2727'}).addTo(layers);}});
 }else{say('The game map library is not ready. Close and reopen this tool after the game finishes loading.');$('[data-preview]').disabled=true;}
 function render(){if(!map)return;layers.clearLayers();if(geometry)L.geoJSON(geometry,{style:{color:'#ed2727',weight:2,fillOpacity:.05}}).addTo(layers);for(const g of exclusions)L.geoJSON(g,{style:{color:'#e8b15b',weight:2,fillOpacity:.2}}).addTo(layers);
 for(const b of records.filter(b=>Number(b.building_type)===22))L.circleMarker([b.latitude,b.longitude],{radius:4,color:'#9ab1c4'}).addTo(layers);
 for(const p of proposal?.sites||[]){const marker=L.marker([p[1],p[0]],{draggable:true,icon:L.divIcon({className:'hr-proposed',iconSize:[12,12]})}).addTo(layers);marker.on('dragend',()=>{const ll=marker.getLatLng(),q=[ll.lng,ll.lat],spacing=Number($('[data-spacing]').value);const others=[...records.filter(b=>Number(b.building_type)===22).map(b=>[b.longitude,b.latitude]),...proposal.sites.filter(x=>x!==p)];if(!contains(geometry,q)||exclusions.some(g=>contains(g,q))||others.some(x=>distanceMiles(x,q)<spacing)){marker.setLatLng([p[1],p[0]]);say('That position is outside the area or too close to another location.');return;}p.splice(0,2,...q);summary();});marker.on('click',()=>{if(busy)return;proposal.sites=proposal.sites.filter(x=>x!==p);render();summary();});}
 }
 function summary(){if(!proposal)return;const count=proposal.sites.length,total=count*(10000+selectedVehicle().credits);$('[data-build]').disabled=!count||total>Number($('[data-budget]').value);say(`${count} proposed · estimated ${total.toLocaleString()} Credits including vehicles · ${records.filter(b=>Number(b.building_type)===22).length} existing Home Responses checked.${proposal.limitReached?' Building limit reached; this is a partial plan.':''} Review roads, exclusions and crew requirements.`);}
 const safe=fn=>async()=>{try{await fn();}catch(e){say(e.message);}};
 $('[data-close]').onclick=()=>{if(busy){say('Pause the build queue before closing.');return;}map?.remove();dialog.remove();dialog=null;};dialog.addEventListener('cancel',e=>{e.preventDefault();$('[data-close]').click();});
 $('[data-controls]').addEventListener('change',e=>{if(e.target.matches('[data-mode],[data-places]'))return;invalidate();training();});
 $('[data-finish]').onclick=safe(()=>{if(drawn.length<3)throw Error('Click at least three boundary corners.');const g={type:'Polygon',coordinates:[[...drawn,[...drawn[0]]]]};if($('[data-mode]').value==='exclude')exclusions.push(g);else geometry=g;drawn=[];invalidate();render();});
 $('[data-clear]').onclick=()=>{exclusions=[];drawn=[];invalidate();render();};
 $('[data-search]').onclick=safe(async()=>{const q=$('[data-city]').value.trim();if(!q)throw Error('Enter a city or town.');if(Date.now()-searchAt<1500)throw Error('Please wait a moment before searching again.');searchAt=Date.now();$('[data-search]').disabled=true;say('Finding UK area boundaries…');try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=gb&polygon_geojson=1&limit=5&q='+encodeURIComponent(q),{credentials:'omit',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Area search unavailable. Use a point and radius or draw your boundary.');places=await r.json();$('[data-places]').replaceChildren(new Option('Choose a result',''));places.forEach((p,i)=>$('[data-places]').add(new Option(p.display_name,String(i))));say('Choose a result. Boundary data: © OpenStreetMap contributors.');}finally{$('[data-search]').disabled=false;}});
 $('[data-places]').onchange=safe(()=>{if($('[data-places]').value==='')return;const p=places[Number($('[data-places]').value)];if(!p)return;const center=[Number(p.lon),Number(p.lat)];geometry=['Polygon','MultiPolygon'].includes(p.geojson?.type)?p.geojson:circle(center,Number($('[data-radius]').value));if(!['Polygon','MultiPolygon'].includes(p.geojson?.type))say('No boundary supplied: using the selected radius.');invalidate();render();map.fitBounds(L.geoJSON(geometry).getBounds());});
 $('[data-preview]').onclick=safe(async()=>{invalidate();if(!geometry)throw Error('Choose an area first.');$('[data-preview]').disabled=true;try{say('Checking your existing buildings…');const a=await api.account();accountId=String(a.user_id);records=await api.buildings();const dispatch=$('[data-dispatch]'),previous=dispatch.value;dispatch.replaceChildren(new Option('Unassigned',''));records.filter(b=>Number(b.building_type)===7).forEach(b=>dispatch.add(new Option(b.caption??b.name,String(b.id))));dispatch.value=previous;
 proposal=plan({geometry,excluded:exclusions,spacingMiles:Number($('[data-spacing]').value),existing:records.filter(b=>Number(b.building_type)===22).map(b=>[b.longitude,b.latitude]),maxBuildings:Number($('[data-limit]').value)});render();summary();const old=window.localStorage.getItem(key());if(old){const parsed=JSON.parse(old);if(parsed.account===accountId&&parsed.state!=='complete'){job=parsed;$('[data-resume]').disabled=false;report();}}}finally{$('[data-preview]').disabled=false;}});
 $('[data-stop]').onclick=()=>{stop=true;say('Pausing after the current request is checked.');};
 async function execute(){if(!navigator.locks?.request)throw Error('This browser cannot lock the build queue across tabs. Use a browser supporting Web Locks for construction.');
 await navigator.locks.request('mcms-home-response-build',{ifAvailable:true},async lock=>{if(!lock)throw Error('Another tab is running Home Response Builder.');const stored=window.localStorage.getItem(key());if(stored){const fresh=JSON.parse(stored);if(fresh.account!==accountId)throw Error('Saved account mismatch.');if(fresh.id===job.id)job=fresh;else if(fresh.state!=='complete')throw Error('Another saved build plan must be resolved first.');}await api.checkAccount(job.account);const count=job.items.filter(i=>!['complete','skipped'].includes(i.state)).length;if(!window.confirm(`Build/equip up to ${count} locations with ${job.vehicle.name}? Maximum total budget: ${job.budget.toLocaleString()} Credits. Already recorded spending: ${job.spent.toLocaleString()} Credits. This makes real game changes. Crew training is not included.`)){if(job.state==='ready')job=null;return;}busy=true;stop=false;$('[data-controls]').disabled=true;$('[data-build]').disabled=true;$('[data-resume]').disabled=true;$('[data-stop]').disabled=false;
 try{await runQueue(job,api,{save,stopped:()=>stop});say(job.state==='complete'?'Build plan completed. Check vehicle crew readiness.':'Paused. Completed work is saved.');}finally{busy=false;$('[data-controls]').disabled=false;$('[data-stop]').disabled=true;$('[data-resume]').disabled=job.state==='complete';report();}});}
 $('[data-build]').onclick=safe(async()=>{if(!proposal?.sites.length)throw Error('Generate a preview first.');if(job&&job.state!=='complete')throw Error('Finish or inspect the saved plan before starting another.');const name=$('[data-name]').value.trim();if(!name)throw Error('Enter a name prefix.');const budget=Number($('[data-budget]').value);if(!Number.isFinite(budget)||budget<proposal.sites.length*(10000+selectedVehicle().credits))throw Error('Budget is below the estimated plan cost.');const id=Date.now().toString(36);job={account:accountId,id,vehicle:selectedVehicle(),spacingMiles:Number($('[data-spacing]').value),dispatchId:$('[data-dispatch]').value,budget,spent:0,state:'ready',items:proposal.sites.map((point,i)=>({point:[...point],name:`${name} ${i+1} [${id}]`,state:'ready'}))};await execute();});
 $('[data-resume]').onclick=safe(execute);
 // Restore the account-scoped checkpoint on opening; no new area selection is needed.
 void (async()=>{try{const a=await api.account();if(!rootDialog.isConnected||busy)return;accountId=String(a.user_id);const stored=window.localStorage.getItem(key());if(!stored)return;const saved=JSON.parse(stored);if(saved.account!==accountId||!Array.isArray(saved.items)||saved.state==='complete')return;job=saved;$('[data-resume]').disabled=false;report();say('Saved build plan found. Review & resume checks any interrupted purchase against the game before continuing.');}catch(e){if(rootDialog.isConnected)say(e.message);}})();

}
