const el=id=>document.getElementById(id);let draft=null,destinationId=null;
async function call(op,extra={}){const r=await sendRuntimeMessage({op,...extra});if(!r?.ok)throw Error(r?.error||'Extension connection unavailable.');return r.value;}
async function refresh(){const s=await call('discordStatus');draft=s.draft;destinationId=s.destinationId;el('destination').textContent=s.configured?`Saved destination: ${s.label}`:'No destination saved.';el('label').value=s.label;el('preview').replaceChildren();for(const e of draft?.payload.embeds||[]){const a=document.createElement('article');for(const t of [e.title,e.description,...(e.fields||[]).map(f=>`${f.name}\n${f.value}`),e.footer?.text])if(t){const p=document.createElement('p');p.textContent=t;a.append(p);}el('preview').append(a);}if(draft?.chart){const img=document.createElement('img');img.src=draft.chart;img.alt='Chart attached to this report';img.style.maxWidth='100%';el('preview').append(img);}el('report-state').textContent=draft?`Report status: ${draft.state}. ${draft.context?.scope?'Source: '+draft.context.scope+'. ':''}Prepared ${new Date(draft.created).toLocaleString()}.`:'No report prepared yet.';el('send').disabled=!s.configured||!draft||!['ready','rate-limited'].includes(draft.state);}
function action(id,run){el(id).addEventListener('click',async()=>{const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{el('status').textContent=await run()||'Done.';}catch(e){el('status').textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);try{await refresh();}catch(e){el('status').textContent=e.message;el('send').disabled=true;}}});}
action('save',async()=>{await call('discordSave',{url:el('webhook').value,label:el('label').value});el('webhook').value='';return 'Destination saved.';});
action('clear',async()=>{if(!confirm('Forget this destination and the prepared report?'))return 'Kept destination.';await call('discordClear');return 'Destination and report removed.';});
action('test',async()=>{const r=await call('discordTest');return `Connected to ${r.name}. No message was sent.`;});
action('send',async()=>{await call('discordSend',{draftId:draft?.id,destinationId});return 'Discord confirmed delivery.';});
action('refresh',async()=> 'Report refreshed.');
refresh().catch(e=>{el('status').textContent=e.message;});
