/* Native Awards enhancement. Reads rendered game cards; never changes progress. */
(function(root){
'use strict';
function readAwards(doc){
 const seen=new Set();return Array.from(doc.querySelectorAll('#collection .collection:not(.always-hidden)')).flatMap(el=>{
  const name=el.querySelector('.panel-title')?.textContent.trim();if(!name)return [];
  const content=el.querySelector('.grid-item-text'),description=Array.from(content?.childNodes||[]).filter(n=>n.nodeType===3).map(n=>n.textContent.trim()).filter(t=>t&&!/^[\d\s,.]+\s+of\s+[\d\s,.]+$/i.test(t)).join(' ');
  const raw=content?.textContent||'',match=raw.match(/([\d,\s]+)\s+of\s+([\d,\s]+)/i),completed=!!el.querySelector('.label-award-gold');
  const current=match?Number(match[1].replace(/\D/g,'')):null,target=match?Number(match[2].replace(/\D/g,'')):null;
  const valid=Number.isSafeInteger(current)&&Number.isSafeInteger(target)&&current>=0&&target>0;
  const rawImage=el.querySelector('img')?.getAttribute('src')||'';let image='';try{const u=new URL(rawImage,doc.location?.href||'https://www.missionchief.co.uk/auszeichnungen');if(u.protocol==='https:'&&(u.hostname==='www.missionchief.co.uk'||u.hostname==='missionchief.co.uk'||u.hostname.endsWith('.missionchief.co.uk')||u.hostname==='leitstellenspiel.s3.amazonaws.com'))image=u.href;}catch{}
  const key=name+'|'+rawImage;if(seen.has(key))return [];seen.add(key);
  const event=/event|summer|autumn|winter|spring|easter|halloween|pumpkin|sunflower|christmas|football|alliance challenge/i.test(name+' '+description);
  const tier=rawImage.match(/award_(gold|silver|bronze)/i)?.[1]||'';
  return [{key,name,description,image,completed,event,tier,current:valid?current:null,target:valid?target:null,percent:completed?100:valid?Math.min(100,current/target*100):null,remaining:valid?Math.max(0,target-current):null}];
 });
}
function selectAwards(items,{query='',status='all',category='all',sort='progress',pins=[]}={}){
 const needle=query.trim().toLowerCase();return items.filter(a=>(!needle||(a.name+' '+a.description).toLowerCase().includes(needle))&&(category==='all'||(category==='events')===a.event)&&(status==='all'||status==='completed'&&a.completed||status==='progress'&&!a.completed&&a.current>0||status==='new'&&!a.completed&&a.current===0||status==='pinned'&&pins.includes(a.key))).sort((a,b)=>sort==='original'?0:sort==='name'?a.name.localeCompare(b.name):Number(a.completed)-Number(b.completed)||(sort==='remaining'?(a.remaining??Infinity)-(b.remaining??Infinity):(b.percent??-1)-(a.percent??-1))||a.name.localeCompare(b.name));
}
function mount(doc,storage){
 const original=doc.querySelector('#iframe-inside-container'),collection=doc.querySelector('#collection');if(!original||!collection||doc.getElementById('tkb-awards'))return null;
 const items=readAwards(doc);if(!items.length)return null;
 const host=doc.createElement('section');host.id='tkb-awards';const shadow=host.attachShadow({mode:'open'});
 shadow.innerHTML=`<style>
 :host{display:block;color:#eef0f3;font:14px/1.5 system-ui,-apple-system,sans-serif;color-scheme:dark}*{box-sizing:border-box}[hidden]{display:none!important}.shell{background:#121416;padding:clamp(16px,3vw,36px);border-top:3px solid #f13d43;min-height:100vh}header{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}small{color:#ff656b;font-weight:750;letter-spacing:.12em}h1{font-size:32px;letter-spacing:-.04em;margin:4px 0}h2{font-size:19px;margin:24px 0 12px}p{margin:8px 0;color:#bbc2cb}button,input,select{font:inherit;border:1px solid #454b53;border-radius:7px;background:#23272c;color:#fff;padding:9px 12px}button{cursor:pointer}button:hover{border-color:#ff656b}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #ff7378;outline-offset:3px}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin:22px 0}.stat{background:#202328;border:1px solid #353a42;border-radius:10px;padding:16px}.stat strong{font-size:27px;display:block}.stat span{color:#c2c8d1}.toolbar{display:flex;gap:12px;flex-wrap:wrap;padding:14px;background:#1b1e22;border-radius:10px;position:sticky;top:0;z-index:2}.toolbar label{display:flex;flex-direction:column;gap:5px;font-size:12px}.toolbar input{min-width:200px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:14px}.card{background:#202328;border:1px solid #3d424a;border-radius:12px;padding:18px;display:flex;flex-direction:column;min-width:0}.card.complete{border-color:#8c763c;background:linear-gradient(135deg,#30291c,#202328 70%)}.card-top{display:flex;gap:15px;align-items:center}.card img{width:70px;height:94px;object-fit:contain}.card h3{font-size:16px;margin:0 0 5px}.tag{font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#c5ccd5}.complete .tag{color:#f2ce72}.card p{font-size:13px;flex:1}.progress{height:7px;background:#101215;border-radius:9px;overflow:hidden;margin:12px 0 7px}.fill{height:100%;background:#ef4b53}.complete .fill{background:#dbb95a}.numbers{display:flex;justify-content:space-between;gap:10px;font-size:12px}.remaining{font-weight:700;color:#fff}.pin{align-self:flex-start;margin-top:14px;font-size:12px;padding:5px 9px}.pin[aria-pressed=true]{border-color:#d9b958;color:#f2d78c}.compact .grid{grid-template-columns:repeat(auto-fill,minmax(220px,1fr))}.compact .card{padding:12px}.compact .card img{width:42px;height:58px}.compact .card p{display:none}footer{margin-top:24px;color:#9ea7b3;font-size:12px}@media(max-width:500px){h1{font-size:26px}.toolbar{position:static}.toolbar label,.toolbar input{width:100%}.grid{grid-template-columns:1fr}}
 </style><div class="shell"><header><div><small>MAP COMMAND TOOLKIT</small><h1>Your awards</h1><p>Your achievements. Your next targets.</p></div><button data-original>Show original page</button></header><main><div class="stats" data-stats></div><section data-goals><h2>Pinned goals</h2><div class="grid" data-pins></div></section><section data-near><h2>Within reach · everyday awards</h2><p>Closest unfinished everyday awards by completion percentage. Event availability is not assumed.</p><div class="grid" data-nearest></div></section><h2>Award collection</h2><div class="toolbar"><label>Search<input type="search" data-query placeholder="Find an award…"></label><label>Status<select data-status><option value="all">All awards</option><option value="progress">In progress</option><option value="completed">Completed</option><option value="new">Not started</option><option value="pinned">Pinned</option></select></label><label>Category<select data-category><option value="all">All categories</option><option value="everyday">Everyday</option><option value="events">Events &amp; seasonal</option></select></label><label>Sort<select data-sort><option value="progress">Closest by percentage</option><option value="remaining">Fewest remaining</option><option value="name">Name A–Z</option><option value="original">Game order</option></select></label><label>Layout<select data-layout><option value="showcase">Showcase</option><option value="compact">Compact</option></select></label></div><p data-count role="status"></p><div class="grid" data-collection></div><footer>Progress comes directly from this game page. Reload to update it. Medal artwork can show the next target, not an earned medal. Event grouping uses award names and descriptions; it does not confirm an event is currently available. Pins are saved on this browser.</footer></main></div>`;
 const $=s=>shadow.querySelector(s),key='toolkit:awards:'+doc.location.origin;let pins=[],showOriginal=false,disposed=false;const state={query:'',status:'all',category:'all',sort:'progress'};
 const originalHidden=original.hidden;original.before(host);original.hidden=true;
 const text=(tag,value,parent)=>{const n=doc.createElement(tag);n.textContent=value;parent.append(n);return n;};
 function cards(list,parent){parent.replaceChildren();for(const a of list){const c=text('article','',parent);c.className='card'+(a.completed?' complete':'');const top=text('div','',c);top.className='card-top';if(a.image){const img=doc.createElement('img');img.src=a.image;img.alt='';img.loading='lazy';top.append(img);}const title=text('div','',top);text('h3',a.name,title);text('span',a.completed?'Gold earned':a.tier?'Next medal: '+a.tier:'Award in progress',title).className='tag';text('p',a.description,c);if(a.percent!==null){const track=text('div','',c);track.className='progress';track.setAttribute('role','progressbar');track.setAttribute('aria-label',a.name);track.setAttribute('aria-valuenow',String(Math.round(a.percent)));track.setAttribute('aria-valuemin','0');track.setAttribute('aria-valuemax','100');const fill=text('div','',track);fill.className='fill';fill.style.width=a.percent+'%';}const row=text('div','',c);row.className='numbers';text('span',a.completed?'Completed':a.target!==null?a.current.toLocaleString()+' / '+a.target.toLocaleString():'Progress unavailable',row);text('span',a.completed?'✓':a.remaining!==null?a.remaining.toLocaleString()+' remaining':'',row).className='remaining';const pin=text('button',pins.includes(a.key)?'★ Pinned':'☆ Pin goal',c);pin.type='button';pin.className='pin';pin.setAttribute('aria-pressed',String(pins.includes(a.key)));pin.setAttribute('aria-label',(pins.includes(a.key)?'Unpin ':'Pin ')+a.name);pin.onclick=()=>{pins=pins.includes(a.key)?pins.filter(k=>k!==a.key):[...pins,a.key];void storage.set({[key]:{pins}}).catch(()=>{$('[data-count]').textContent='Could not save pins. They remain selected for this visit.';});render();};}}
 function render(){const done=items.filter(a=>a.completed).length;const stats=$('[data-stats]');stats.replaceChildren();for(const [value,label] of [[items.length,'Award entries'],[done,'Completed to gold'],[items.filter(a=>!a.completed&&a.current>0).length,'In progress'],[pins.filter(k=>items.some(a=>a.key===k)).length,'Pinned goals']]){const n=text('div','',stats);n.className='stat';text('strong',String(value),n);text('span',label,n);}const pinned=items.filter(a=>pins.includes(a.key));$('[data-goals]').hidden=!pinned.length;cards(pinned,$('[data-pins]'));const near=selectAwards(items,{category:'everyday'}).filter(a=>!a.completed&&a.target!==null).slice(0,3);$('[data-near]').hidden=!near.length;cards(near,$('[data-nearest]'));const filtered=selectAwards(items,{...state,pins});cards(filtered,$('[data-collection]'));$('[data-count]').textContent=filtered.length+' of '+items.length+' awards'+(!filtered.length?' — no matches. Change your search or filters.':'');}
 for(const field of ['query','status','category','sort'])$('[data-'+field+']').addEventListener(field==='query'?'input':'change',e=>{state[field]=e.target.value;render();});
 $('[data-layout]').onchange=e=>$('.shell').classList.toggle('compact',e.target.value==='compact');
 $('[data-original]').onclick=()=>{showOriginal=!showOriginal;original.hidden=showOriginal?originalHidden:true;$('main').hidden=showOriginal;$('.shell').style.minHeight=showOriginal?'0':'';$('[data-original]').textContent=showOriginal?'Show Toolkit awards':'Show original page';};
 render();void storage.get(key).then(v=>{if(disposed)return;pins=Array.isArray(v[key]?.pins)?v[key].pins.filter(k=>typeof k==='string').slice(0,200):[];render();}).catch(()=>{});
 return {destroy(){disposed=true;original.hidden=originalHidden;host.remove();},items,shadow};
}
if(typeof module!=='undefined'&&module.exports){module.exports={readAwards,selectAwards,mount};return;}
if(!/^\/auszeichnungen\/?$/.test(location.pathname))return;
let view=null;async function start(){const config=await chrome.storage.local.get('enabled');if(config.enabled===false){view?.destroy();view=null;return;}if(!view)view=mount(document,chrome.storage.local);}void start();chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.enabled)void start();});
})(this);
