/* Player overview derived exclusively from the profile currently on screen. */
(function(){'use strict';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim(),fmt=n=>Number(n).toLocaleString('en-GB');
function readProfile(doc,now=Date.now()){
 const info=doc.querySelector('#userinfo'),raw=info?.getAttribute('data-credits-earned'),credits=raw!==null&&/^\d+$/.test(raw||'')?Number(raw):null;
 const signup=Date.parse(doc.querySelector('#signup_date')?.getAttribute('data-signup-date')||''),days=Number.isFinite(signup)&&signup<=now?Math.floor((now-signup)/86400000):null;
 const awards=Array.from(doc.querySelectorAll('#profile_awards .grid-item')).map(el=>({el,name:clean(el.querySelector('.panel-title')?.textContent),tier:(el.querySelector('img')?.getAttribute('src')||'').match(/award_(gold|silver|bronze)_/)?.[1]||'other'}));
 return {credits,days,signup,awards};
}
function milestone(credits){if(!Number.isFinite(credits)||credits<0)return null;const scale=10**Math.max(3,Math.floor(Math.log10(Math.max(1,credits))));const target=(Math.floor(credits/scale)+1)*scale;return {target,remaining:target-credits,percent:credits/target*100};}
function stations(doc){return Array.from(doc.querySelectorAll('#profile_map .leaflet-marker-pane .leaflet-marker-icon[title]')).map(el=>({el,name:clean(el.getAttribute('title'))})).filter(x=>x.name).sort((a,b)=>a.name.localeCompare(b.name));}
function mount(doc){const container=doc.querySelector('#iframe-inside-container'),info=container?.querySelector('#userinfo');if(!info?.querySelector('h1')||!container.querySelector('#tabs')||doc.getElementById('tkb-profile-dashboard'))return null;
 let original=false,disposed=false,timer=null,limit=30,lastMarkers=[],lastSignature='';const model=readProfile(doc),host=doc.createElement('section');host.id='tkb-profile-dashboard';
 host.innerHTML='<div class="tkbp-top"><span>PLAYER OVERVIEW</span><button type="button" data-original>Show original page</button></div><div data-content><div class="tkbp-stats" data-stats></div><div class="tkbp-lower"><section class="tkbp-milestone"><small>NEXT CREDIT MILESTONE</small><h2 data-target></h2><p data-remaining></p><progress data-progress max="100"></progress><p class="tkbp-note">A round-number lifetime-credit goal, not a game rank requirement.</p></section><section class="tkbp-honours"><small>TROPHY CABINET</small><div data-medals class="tkbp-medals"></div><p class="tkbp-note">Awards displayed on this profile. Each award is counted once at its displayed tier.</p><button type="button" data-awards>Explore awards →</button></section></div></div>';
 info.after(host);container.classList.add('tkbp-enhanced');const $=s=>host.querySelector(s),owned=[];
 const add=(tag,text,parent,cls)=>{const el=doc.createElement(tag);el.textContent=text;if(cls)el.className=cls;parent.append(el);return el;};
 const stats=$('[data-stats]');for(const [value,label,note] of [[model.credits===null?'—':fmt(model.credits),'Lifetime credits','Total earned, not current balance'],[model.days===null?'—':fmt(model.days),'Days since joining','Calendar days, not active play time'],[model.days>0&&model.credits!==null?fmt(Math.round(model.credits/model.days)):'—','Credits / calendar day','Lifetime average since signup'],[fmt(model.awards.length),'Displayed awards','From this profile’s trophy collection']]){const card=add('div','',stats,'tkbp-stat');add('small',label,card);add('strong',value,card);add('span',note,card);}
 const goal=milestone(model.credits);$('[data-target]').textContent=goal?fmt(goal.target)+' credits':'Credits unavailable';$('[data-remaining]').textContent=goal?fmt(goal.remaining)+' to go · '+goal.percent.toFixed(1)+'% of goal':'The game did not provide a lifetime total.';$('[data-progress]').value=goal?.percent||0;$('[data-progress]').setAttribute('aria-label','Progress towards lifetime credit milestone');
 for(const tier of ['gold','silver','bronze','other']){const count=model.awards.filter(x=>x.tier===tier).length;if(tier==='other'&&!count)continue;const card=add('div','',$('[data-medals]'),'tkbp-medal '+tier);add('strong',fmt(count),card);add('span',tier==='other'?'Other':tier[0].toUpperCase()+tier.slice(1),card);}
 $('[data-awards]').onclick=()=>container.querySelector('#tabs a[href="#profile_awards"]')?.click();
 // Native links, user biography, map and award nodes remain in place.
 const avatar=container.querySelector('#profile_text_photo .profile_avatar');if(avatar){const image=doc.createElement('img');image.className='tkbp-avatar';image.src=avatar.getAttribute('src');image.alt='Profile picture';image.setAttribute('aria-hidden','true');info.prepend(image);owned.push(image);}
 const eyebrow=doc.createElement('div');eyebrow.className='tkbp-eyebrow';eyebrow.textContent='MISSIONCHIEF • PLAYER DOSSIER';info.prepend(eyebrow);owned.push(eyebrow);
 const awardPanel=container.querySelector('#profile_awards'),awardTools=doc.createElement('div');awardTools.className='tkbp-award-tools';awardTools.innerHTML='<label>Search awards<input type="search" data-award-search placeholder="Name or event…"></label><label>Tier<select data-tier><option value="all">All tiers</option><option value="gold">Gold</option><option value="silver">Silver</option><option value="bronze">Bronze</option><option value="other">Other</option></select></label><span role="status" data-award-count></span>';
 if(awardPanel){awardPanel.prepend(awardTools);owned.push(awardTools);}
 function filterAwards(){const query=awardTools.querySelector('input').value.toLowerCase(),tier=awardTools.querySelector('select').value;let count=0;for(const a of model.awards){const match=a.name.toLowerCase().includes(query)&&(tier==='all'||tier===a.tier);a.el.setAttribute('data-tkb-profile-filtered',String(!match));if(match)count++;}awardTools.querySelector('[data-award-count]').textContent=count+' of '+model.awards.length+' awards';}
 awardTools.querySelector('input').oninput=filterAwards;awardTools.querySelector('select').onchange=filterAwards;filterAwards();
 const directory=doc.createElement('section');directory.className='tkbp-directory';directory.innerHTML='<div class="tkbp-directory-head"><div><small>STATION DIRECTORY</small><h2>Explore the network</h2></div><span data-station-count></span></div><p class="tkbp-note">Buildings currently loaded on this profile map. This may not include every building owned.</p><label class="tkbp-search">Find a building<input type="search" data-station-search placeholder="Search by station name…"></label><div data-stations class="tkbp-stations"></div><p data-station-status role="status"></p><button type="button" data-more>Show more</button>';
 const mapPanel=container.querySelector('#profile_map');if(mapPanel){mapPanel.append(directory);owned.push(directory);}
 const query=directory.querySelector('input'),list=directory.querySelector('[data-stations]'),more=directory.querySelector('[data-more]');
 function refreshDirectory(force=false){if(disposed||original)return;const items=stations(doc),signature=items.map(x=>x.name).join('\n');if(!force&&signature===lastSignature&&items.every((x,i)=>x.el===lastMarkers[i]))return;lastSignature=signature;lastMarkers=items.map(x=>x.el);const matching=items.filter(x=>x.name.toLowerCase().includes(query.value.toLowerCase()));list.replaceChildren();for(const item of matching.slice(0,limit)){const b=add('button',item.name,list);b.type='button';b.title='Open this building’s map marker';b.onclick=()=>{if(item.el.isConnected){item.el.click();mapPanel.querySelector('#map')?.scrollIntoView?.({block:'nearest'});}};}directory.querySelector('[data-station-count]').textContent=fmt(items.length)+' loaded markers';directory.querySelector('[data-station-status]').textContent=items.length?Math.min(limit,matching.length)+' of '+matching.length+' matching buildings': 'No building markers loaded yet, or this profile has no visible buildings.';more.hidden=matching.length<=limit;}
 query.oninput=()=>{limit=30;refreshDirectory(true);};more.onclick=()=>{limit+=30;refreshDirectory(true);};
 function appearance(){container.classList.toggle('tkbp-enhanced',!original);$('[data-content]').hidden=original;for(const el of owned)el.hidden=original;$('[data-original]').textContent=original?'Show Toolkit profile':'Show original page';if(!original)refreshDirectory(true);}
 $('[data-original]').onclick=()=>{original=!original;appearance();};
 const style=doc.createElement('style');style.textContent=CSS;doc.head.append(style);refreshDirectory(true);
 const Observer=doc.defaultView?.MutationObserver;const markers=mapPanel?.querySelector('#map');let observer;if(Observer&&markers){observer=new Observer(()=>{if(timer||disposed)return;timer=doc.defaultView.setTimeout(()=>{timer=null;refreshDirectory();},200);});observer.observe(markers,{childList:true,subtree:true,attributes:true,attributeFilter:['title']});}
 return {host,refresh:()=>refreshDirectory(true),destroy(){disposed=true;observer?.disconnect();if(timer)doc.defaultView.clearTimeout(timer);container.classList.remove('tkbp-enhanced');for(const a of model.awards)a.el.removeAttribute('data-tkb-profile-filtered');for(const el of owned)el.remove();host.remove();style.remove();}};
}
const CSS=`
#tkb-profile-dashboard{font:14px/1.5 system-ui,sans-serif;color:#edf2f5;margin:0 0 22px}#tkb-profile-dashboard *,.tkbp-directory *,.tkbp-award-tools *{box-sizing:border-box}
.tkbp-enhanced{background:#090c0f!important;color:#dce2e7!important;padding:22px!important;min-height:100vh}
.tkbp-enhanced #userinfo{position:relative;overflow:hidden;border:1px solid #384148;border-top:3px solid #ed394e;border-radius:14px;padding:26px;margin:0 0 16px;background:radial-gradient(ellipse at 90% 0,rgba(214,38,63,.18),transparent 60%),linear-gradient(120deg,#191f25,#101419);color:#c6ced6;line-height:1.9;box-shadow:0 16px 35px #0003}
.tkbp-enhanced #userinfo h1{color:#fff;font:800 clamp(26px,4vw,42px)/1.2 system-ui;margin:12px 0;letter-spacing:-1px;overflow-wrap:anywhere}
.tkbp-enhanced #userinfo a{color:#a8dcff}.tkbp-enhanced #userinfo .btn{background:#20272d;border-color:#4c565f;color:#fff;margin:2px;padding:6px 10px}
.tkbp-eyebrow{font:800 10px/1.4 system-ui;letter-spacing:2px;color:#ff7d8d;margin-bottom:12px}.tkbp-avatar{float:left;width:105px;height:105px;object-fit:contain;background:#0c1014;border:1px solid #48515b;border-radius:16px;padding:8px;margin:12px 22px 30px 0}
.tkbp-top{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:12px 0}.tkbp-top>span{color:#9ca9b4;font-size:10px;font-weight:800;letter-spacing:2px}
#tkb-profile-dashboard button,.tkbp-directory button{border:1px solid #48535d;background:#1a222a;border-radius:7px;padding:9px 13px;color:#e9eff4;cursor:pointer;font:600 12px/1.4 system-ui}#tkb-profile-dashboard button:hover,.tkbp-directory button:hover{background:#32232b;border-color:#ff6b80}
.tkbp-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.tkbp-stat{padding:20px 16px;background:linear-gradient(145deg,#1b232b,#11171c);border:1px solid #35414a;border-radius:10px}.tkbp-stat small{display:block;color:#b1bec8;text-transform:uppercase;letter-spacing:1px;font-size:10px}.tkbp-stat strong{display:block;color:#fff;font-size:clamp(19px,2.6vw,32px);font-variant-numeric:tabular-nums;margin:9px 0}.tkbp-stat span{font-size:11px;color:#a2b0bb}
.tkbp-lower{display:grid;grid-template-columns:1.2fr 1fr;gap:12px;margin-top:12px}.tkbp-lower section{padding:20px;border:1px solid #35414a;border-radius:10px;background:#131a20}.tkbp-lower small,.tkbp-directory small{font:800 10px system-ui;letter-spacing:1.5px;color:#ff8292}.tkbp-lower h2,.tkbp-directory h2{font:750 23px/1.3 system-ui;color:#fff;margin:10px 0}.tkbp-note{font:12px/1.6 system-ui;color:#a6b4be;margin:10px 0}.tkbp-milestone progress{width:100%;height:9px;appearance:none;border:none;border-radius:5px;overflow:hidden;background:#2b3741;accent-color:#f14a64}.tkbp-milestone progress::-webkit-progress-bar{background:#2b3741}.tkbp-milestone progress::-webkit-progress-value{background:linear-gradient(90deg,#a71933,#ff6d83)}
.tkbp-medals{display:flex;gap:22px;margin:16px 0}.tkbp-medal strong{display:block;font-size:30px;line-height:1.1}.tkbp-medal span{font-size:11px;color:#c8d0d8}.tkbp-medal.gold{color:#eac86b}.tkbp-medal.silver{color:#d0dfe9}.tkbp-medal.bronze{color:#d89b70}
.tkbp-enhanced #tabs{display:flex;gap:8px;border:0;margin:18px 0;background:#11181e;padding:6px;border-radius:10px}.tkbp-enhanced #tabs>li{float:none;flex:1;text-align:center;margin:0}.tkbp-enhanced #tabs>li>a{color:#c6d3dc;background:transparent;border:0;border-radius:7px;font-weight:700}.tkbp-enhanced #tabs>li.active>a{background:#962239;color:#fff}.tkbp-enhanced #profile_map #map{border:1px solid #3c4853;border-radius:10px;overflow:hidden}
.tkbp-enhanced #profile_text_photo{padding:24px;background:#131b22;border:1px solid #35414a;border-radius:10px;font:14px/1.85 system-ui;overflow-wrap:anywhere}.tkbp-enhanced #profile_text_photo p{margin-bottom:20px}.tkbp-enhanced #profile_text_photo a{color:#9dd4ff}
.tkbp-enhanced #profile_awards .grid-container{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:14px}.tkbp-enhanced #profile_awards .grid-item{display:flex;flex-direction:column;align-items:center;gap:14px;min-width:0;background:radial-gradient(ellipse at top,#2b2830,#141b21 75%);border:1px solid #43515c;border-radius:12px;padding:22px;text-align:center;color:#d0d9e0;box-shadow:0 8px 20px #0003}.tkbp-enhanced #profile_awards .grid-item-header{background:none;border:0}.tkbp-enhanced #profile_awards .panel-title{font:700 14px/1.4 system-ui;color:#fff}.tkbp-enhanced #profile_awards .grid-item img{float:none!important;max-width:85px;max-height:85px;object-fit:contain;filter:drop-shadow(0 5px 9px #0006)}.tkbp-enhanced #profile_awards .grid-item-text{font:12px/1.6 system-ui;color:#adbbc6}.tkbp-enhanced [data-tkb-profile-filtered=true]{display:none!important}
.tkbp-award-tools{display:flex;flex-wrap:wrap;align-items:end;gap:12px;padding:16px;background:#131b22;border-radius:10px;margin-bottom:16px}.tkbp-award-tools label,.tkbp-search{font:600 12px/1.5 system-ui;color:#bdcad4}.tkbp-award-tools input,.tkbp-award-tools select,.tkbp-search input{display:block;background:#0b1116;color:#eef4f8;border:1px solid #4a5b69;padding:10px;border-radius:6px;margin-top:5px;font:14px system-ui;max-width:100%}
.tkbp-directory{background:#131b22;border:1px solid #35414a;border-radius:10px;padding:20px;margin-top:16px;color:#dce6ee}.tkbp-directory-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.tkbp-directory-head>span{color:#b9c9d5;font:12px system-ui}.tkbp-search{display:block}.tkbp-search input{width:100%}.tkbp-stations{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:14px 0}.tkbp-stations button{text-align:left;overflow-wrap:anywhere;min-height:44px}.tkbp-enhanced button:focus-visible,.tkbp-enhanced a:focus-visible,.tkbp-enhanced input:focus-visible,.tkbp-enhanced select:focus-visible{outline:2px solid #ffb3bf;outline-offset:3px}
#tkb-profile-dashboard [hidden],.tkbp-directory [hidden],.tkbp-award-tools[hidden],.tkbp-directory[hidden],.tkbp-avatar[hidden],.tkbp-eyebrow[hidden]{display:none!important}
@media(max-width:700px){.tkbp-enhanced{padding:12px!important}.tkbp-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.tkbp-lower{grid-template-columns:1fr}.tkbp-stations{grid-template-columns:1fr 1fr}.tkbp-avatar{width:72px;height:72px;margin-right:12px}.tkbp-enhanced #userinfo{padding:16px}.tkbp-enhanced #userinfo .pull-right{float:none!important;display:flex;flex-wrap:wrap}.tkbp-directory-head{align-items:start;flex-direction:column}}@media(max-width:400px){.tkbp-stations{grid-template-columns:1fr}}
`;
if(typeof module!=='undefined'&&module.exports){module.exports={readProfile,milestone,stations,mount,CSS};return;}
if(!/^\/profile\/\d+\/?$/.test(location.pathname))return;let view=null;
async function start(){try{const settings=await chrome.storage.local.get('enabled');if(settings.enabled===false){view?.destroy();view=null;}else if(!view)view=mount(document);}catch{/* Native page remains available. */}}
void start();chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.enabled)void start();});
})();
