/* Enhance native task panels without replacing claim forms or game timers. */
(function(){'use strict';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
function seconds(raw){const t=clean(raw),m=t.match(/(?:(\d+)\s+days?\s*-?\s*)?(\d+):(\d{2}):(\d{2})/i);return m?Number(m[1]||0)*86400+Number(m[2])*3600+Number(m[3])*60+Number(m[4]):null;}
function readTask(el){const title=clean(el.querySelector('.panel-heading')?.textContent),progress=clean(el.querySelector('.progress')?.textContent).match(/([\d,]+)\s*\/\s*([\d,]+)/),current=progress?Number(progress[1].replaceAll(',','')):null,target=progress?Number(progress[2].replaceAll(',','')):null,button=el.querySelector('input[type=submit],button[type=submit]'),countdown=el.querySelector('[id^=task_countdown_]');const rewards=Array.from(el.querySelectorAll('.task_body img')).map(img=>clean(img.parentElement.textContent));return {el,title,current,target,percent:target>0?Math.min(100,current/target*100):null,remaining:target>0?Math.max(0,target-current):null,ready:!!button&&!button.disabled&&!button.hasAttribute('disabled'),seconds:seconds(countdown?.textContent),rewards,credits:rewards.filter(t=>/Credits/i.test(t)).reduce((n,t)=>n+Number(t.match(/[\d,]+/)?.[0].replaceAll(',','')||0),0)};}
function choose(items,{query='',filter='all',sort='priority'}={}){return items.filter(x=>x.title.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='ready'&&x.ready||filter==='progress'&&!x.ready&&x.current>0||filter==='new'&&!x.ready&&x.current===0||filter==='soon'&&x.seconds!==null&&x.seconds<=86400)).sort((a,b)=>sort==='original'?0:sort==='name'?a.title.localeCompare(b.title):sort==='reward'?b.credits-a.credits:sort==='progress'?(b.percent??-1)-(a.percent??-1):sort==='deadline'?(a.seconds??Infinity)-(b.seconds??Infinity):Number(b.ready)-Number(a.ready)||(a.seconds??Infinity)-(b.seconds??Infinity)||(b.percent??-1)-(a.percent??-1));}
function mount(doc){const container=doc.querySelector('#iframe-inside-container');if(!container||!container.querySelector('.task_panel.hidden-xs')||doc.getElementById('tkb-tasks-toolbar'))return null;
 const panes=Array.from(container.querySelectorAll('.task-tab-content')),records=[],host=doc.createElement('section');host.id='tkb-tasks-toolbar';host.innerHTML='<div class="tkb-task-header"><div><small>MAP COMMAND TOOLKIT</small><h2>Your next objectives</h2><p>See what is ready, what is close and what ends soon.</p></div><button type="button" data-original>Show original page</button></div><div data-enhanced><div class="tkb-task-stats" data-stats></div><div class="tkb-task-controls"><label>Search<input data-query type="search" placeholder="Find a task…"></label><label>Show<select data-filter><option value="all">All tasks</option><option value="ready">Ready to claim</option><option value="progress">In progress</option><option value="new">Not started</option><option value="soon">Ends within 24 hours</option></select></label><label>Sort<select data-sort><option value="priority">Ready, then ending soon</option><option value="deadline">Ending soonest</option><option value="progress">Closest to completion</option><option value="reward">Highest credit reward</option><option value="name">Name A–Z</option><option value="original">Game order</option></select></label></div><p data-status role="status"></p><p class="tkb-task-note">Rewards shown are potential rewards, not earnings. Claiming uses the game’s original controls and confirmations.</p></div>';
 const style=doc.createElement('style');style.textContent=`
 #tkb-tasks-toolbar{font:14px/1.5 system-ui,sans-serif;background:#151719;color:#f3f4f6;padding:24px;border-top:3px solid #f3424b;border-radius:10px;margin:16px 0}#tkb-tasks-toolbar *{box-sizing:border-box}#tkb-tasks-toolbar [hidden]{display:none!important}.tkb-task-header{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}#tkb-tasks-toolbar small{color:#ff696f;letter-spacing:.1em;font-weight:750}#tkb-tasks-toolbar h2{font-size:27px;margin:5px 0}#tkb-tasks-toolbar p{color:#bfc5ce;margin:8px 0}#tkb-tasks-toolbar button,#tkb-tasks-toolbar input,#tkb-tasks-toolbar select{background:#25292e;color:#fff;border:1px solid #555e69;padding:9px 12px;border-radius:7px;font:inherit}#tkb-tasks-toolbar :focus-visible{outline:2px solid #ff7279;outline-offset:3px}.tkb-task-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin:20px 0}.tkb-task-stats>div{padding:14px;background:#24272c;border:1px solid #454950;border-radius:8px}.tkb-task-stats strong{display:block;font-size:25px}.tkb-task-stats span{font-size:12px;color:#c0c8d4}.tkb-task-controls{display:flex;gap:12px;flex-wrap:wrap}.tkb-task-controls label{display:flex;flex-direction:column;gap:5px;font-size:12px}.tkb-task-note{font-size:12px}
 .tkb-tasks-enhanced .task_panel.visible-xs{display:none!important}.tkb-tasks-enhanced .task_panel.hidden-xs{display:block!important;border:1px solid #464b53!important;border-left:4px solid #ee4b53!important;border-radius:10px!important;overflow:hidden;background:#202328!important;color:#f3f4f6!important;margin-bottom:14px!important}.tkb-tasks-enhanced .task_panel[data-tkb-filtered=true]{display:none!important}.tkb-tasks-enhanced .task_panel.hidden-xs>.panel-heading{background:#272b31!important;color:#fff!important;border:0!important;font-size:16px!important;padding:16px!important}.tkb-tasks-enhanced .task_panel.hidden-xs .task_body{padding:14px 16px!important}.tkb-tasks-enhanced .task_panel.hidden-xs .task_body>div{flex-wrap:wrap!important;gap:14px!important}.tkb-tasks-enhanced .task_panel .progress{height:23px!important;border-radius:6px!important;background:#111317!important;min-width:150px}.tkb-tasks-enhanced .task_panel .progress-bar{background:#cc3d48!important}.tkb-tasks-enhanced .task_panel[data-tkb-ready=true]{border-left-color:#68d8a4!important}.tkb-tasks-enhanced .task_panel[data-tkb-soon=true] [id^=task_countdown_]{color:#ffcd70;font-weight:bold}.tkb-tasks-enhanced .task_panel .btn{border-radius:7px!important}.tkb-task-detail{font:12px/1.5 system-ui;color:#cbd1da;padding:0 16px 12px}.tkb-tasks-enhanced .task_panel:not([data-tkb-ready=true]) input[type=submit]{opacity:.55}.tkb-tasks-enhanced #tabs a{color:inherit}.tkb-tasks-enhanced .task_panel[data-tkb-ready=true] input[type=submit]{background:#295f48;color:#fff;border-color:#68d8a4}.tkb-task-detail[hidden]{display:none!important}@media(max-width:520px){#tkb-tasks-toolbar{padding:16px}.tkb-task-controls label,.tkb-task-controls input,.tkb-task-controls select{width:100%}.tkb-tasks-enhanced .task_panel.hidden-xs .task_body>div>div{min-width:0!important;max-width:100%}.tkb-tasks-enhanced .task_panel.hidden-xs .task_body>div>div:has(.progress){flex-basis:100%}}
 `;doc.head.append(style);const heading=container.querySelector('.page-header');(heading||container.firstElementChild).after(host);
 for(const pane of panes)for(const el of Array.from(pane.querySelectorAll('.task_panel.hidden-xs'))){const anchor=doc.createComment('Toolkit task original position');el.before(anchor);const detail=doc.createElement('div');detail.className='tkb-task-detail';el.append(detail);records.push({pane,el,anchor,detail});}
 let original=false,lastSignature='',timer;const state={query:'',filter:'all',sort:'priority'},$=s=>host.querySelector(s);container.classList.add('tkb-tasks-enhanced');
 function restore(){for(const r of records){if(r.el.isConnected&&r.anchor.isConnected)r.anchor.after(r.el);r.el.removeAttribute('data-tkb-filtered');r.el.removeAttribute('data-tkb-ready');r.el.removeAttribute('data-tkb-soon');r.detail.hidden=true;}}
 function refresh(){if(original)return;const data=records.filter(r=>r.el.isConnected).map(r=>({...readTask(r.el),record:r})),sig=JSON.stringify(data.map(x=>[x.title,x.current,x.target,x.ready,x.seconds!==null&&x.seconds<=86400,x.seconds===0,x.rewards]))+JSON.stringify(state)+panes.map(p=>p.classList.contains('active'));if(sig===lastSignature)return;lastSignature=sig;
  for(const pane of panes){const all=data.filter(x=>x.record.pane===pane),visible=choose(all,state);for(const x of all){x.el.dataset.tkbFiltered=String(!visible.includes(x));x.el.dataset.tkbReady=String(x.ready);x.el.dataset.tkbSoon=String(x.seconds!==null&&x.seconds<=86400);x.record.detail.hidden=false;x.record.detail.textContent=x.ready?'Ready to claim':x.seconds===0?'Timer ended — refresh the game page to check availability':x.remaining!==null?x.remaining.toLocaleString()+' remaining · '+Math.round(x.percent)+'% complete':'Progress not provided by the game';}for(const x of visible)pane.append(x.el);}
  const active=panes.find(p=>p.classList.contains('active'))||panes[0],all=data.filter(x=>x.record.pane===active),stats=$('[data-stats]');stats.replaceChildren();for(const [value,label] of [[all.length,'Tasks in this tab'],[all.filter(x=>x.ready).length,'Ready to claim'],[all.filter(x=>x.seconds!==null&&x.seconds<=86400).length,'End within 24 hours'],[all.filter(x=>x.ready).reduce((n,x)=>n+x.credits,0).toLocaleString(),'Credits ready to claim']]){const box=doc.createElement('div'),strong=doc.createElement('strong'),span=doc.createElement('span');strong.textContent=value;span.textContent=label;box.append(strong,span);stats.append(box);}$('[data-status]').textContent=choose(all,state).length+' of '+all.length+' tasks shown. Countdown times are maintained by MissionChief.';
 }
 for(const key of ['query','filter','sort'])$('[data-'+key+']').addEventListener(key==='query'?'input':'change',e=>{state[key]=e.target.value;refresh();});
 $('[data-original]').onclick=()=>{original=!original;container.classList.toggle('tkb-tasks-enhanced',!original);$('[data-enhanced]').hidden=original;$('[data-original]').textContent=original?'Show Toolkit tasks':'Show original page';if(original)restore();else{lastSignature='';refresh();}};
 refresh();if(doc.defaultView?.setInterval)timer=doc.defaultView.setInterval(refresh,1000);
 return {host,refresh,destroy(){if(timer)doc.defaultView.clearInterval(timer);restore();for(const r of records){r.detail.remove();r.anchor.remove();}container.classList.remove('tkb-tasks-enhanced');host.remove();style.remove();}};
}
if(typeof module!=='undefined'&&module.exports){module.exports={readTask,choose,seconds,mount};return;}
if(!/^\/tasks\/index\/?$/.test(location.pathname))return;let view=null;async function start(){const config=await chrome.storage.local.get('enabled');if(config.enabled===false){view?.destroy();view=null;return;}if(!view)view=mount(document);}void start();chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&c.enabled)void start();});
})();
