import {iconScope,scanIcons,runIconReplacement} from './core.mjs';
let iconApi,iconDialog,iconBusy=false,iconStop=false;
export function configureIconReplacement(api){iconApi=api;}
export function destroyIconReplacement(){iconStop=true;iconDialog?.remove();}
export function openIconReplacement(){
 if(iconDialog?.isConnected){iconDialog.showModal();return;}
 if(!iconApi)return;
 const d=document.createElement('dialog');iconDialog=d;d.className='tkb-icon-replacer';
 d.innerHTML=`<style>.tkb-icon-replacer{background:#171a1c;color:#eee;border:1px solid #666;border-top:3px solid #e33;border-radius:8px;padding:18px;width:min(950px,94vw);max-height:90dvh;font:14px/1.5 system-ui}.tkb-icon-replacer::backdrop{background:#000a}.tkb-icon-replacer header,.tkb-icon-replacer .controls{display:flex;flex-wrap:wrap;align-items:center;gap:10px}.tkb-icon-replacer header{justify-content:space-between}.tkb-icon-replacer h2{color:#fff;margin:0}.tkb-icon-replacer label{display:grid;gap:4px}.tkb-icon-replacer button,.tkb-icon-replacer select{background:#292d31;color:#fff!important;border:1px solid #777;border-radius:4px;padding:8px;font:inherit;min-height:42px}.tkb-icon-replacer button:disabled{opacity:.5}.tkb-icon-replacer output{display:block;margin:12px 0}.tkb-icon-replacer .pickers{display:grid;grid-template-columns:1fr 1fr;gap:16px}.tkb-icon-replacer .icons{display:flex;flex-wrap:wrap;gap:8px;max-height:240px;overflow:auto}.tkb-icon-replacer .icons button{display:grid;justify-items:center;gap:5px;min-width:90px}.tkb-icon-replacer .icons button[aria-pressed=true]{outline:3px solid #ef4653;background:#492126}.tkb-icon-replacer img{width:50px;height:50px;object-fit:contain}.tkb-icon-replacer .results{max-height:30dvh;overflow:auto;margin:12px 0}.tkb-icon-replacer .results label{grid-template-columns:24px minmax(0,1fr);padding:6px;border-bottom:1px solid #444}.tkb-icon-replacer input{appearance:auto;width:18px;height:18px}.tkb-icon-replacer [data-run]{background:#86232d}@media(max-width:550px){.tkb-icon-replacer .pickers{grid-template-columns:1fr}}.tkb-icon-replacer .progress-panel{position:sticky;top:-18px;z-index:5;background:#22292f!important;color:#fff!important;border:1px solid #929da7;border-left:5px solid #f04454;border-radius:6px;padding:12px 14px;margin:14px 0;box-shadow:0 5px 15px #0005}.tkb-icon-replacer .progress-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.tkb-icon-replacer [data-phase]{color:#fff!important;font-size:16px!important}.tkb-icon-replacer [data-phase]:before{content:'●';color:#ff6271;margin-right:8px}.tkb-icon-replacer [data-working=true] [data-phase]:before{animation:tkb-progress-pulse 1s ease-in-out infinite alternate}.tkb-icon-replacer [data-status]{color:#fff!important;font-size:15px!important;font-weight:600!important;line-height:1.5!important;margin:8px 0!important;opacity:1!important}.tkb-icon-replacer [data-elapsed],.tkb-icon-replacer [data-current]{color:#e0e7ed!important;font-size:12px!important;overflow-wrap:anywhere}.tkb-icon-replacer progress{display:block;width:100%;height:14px;margin:8px 0;accent-color:#ed4656}.tkb-icon-replacer progress::-webkit-progress-bar{background:#434c55;border-radius:4px}.tkb-icon-replacer progress::-webkit-progress-value{background:#ed4656;border-radius:4px}@keyframes tkb-progress-pulse{to{opacity:.3}}@media(prefers-reduced-motion:reduce){.tkb-icon-replacer [data-working=true] [data-phase]:before{animation:none}}</style>
 <header><h2>Replace matching station icons</h2><button data-close>← Back to icon copier</button></header>
 <p>Choose the current icon and its replacement. Only owned buildings with a matching custom image are included. Images are compared by their contents, even when their URLs differ.</p>
 <div class="controls"><label>Building type<select data-type><option value="">All building types</option></select></label><label>Dispatch centre<select data-dispatch><option value="">All dispatch centres</option><option value="0">Unassigned</option></select></label><button data-scan>Scan / refresh icons</button></div>
 <section class="progress-panel" aria-label="Icon replacement progress"><div class="progress-head"><strong data-phase>Loading</strong><span data-elapsed></span></div><output data-status role="status">Loading buildings and saved icons…</output><div data-count></div><progress data-progress aria-label="Progress"></progress><div data-current></div></section>
 <div class="pickers"><section><h3>1. Replace this icon</h3><div class="icons" data-from></div></section><section><h3>2. With this icon</h3><div class="icons" data-to></div></section></div>
 <p>Saved counts are from the last scan. Preview refreshes the selected scope before any change. Default game icons and unreadable images are excluded.</p>
 <div class="controls"><button data-preview>Refresh & preview matches</button><button data-run disabled>Review & replace all selected</button><button data-pause disabled>Pause after current building</button><button data-resume disabled>Review & resume</button><button data-skip>Skip unresolved buildings</button><button data-clear>Discard pending plan</button></div>
 <div class="results" data-results></div>`;
 document.body.append(d);d.showModal();const $=s=>d.querySelector(s),api=iconApi;let account='',records=[],catalogue=null,from='',to='',preview=null,job=null;
 const key=()=>`mcms_icon_replace_v1_${account}`,cacheKey=()=>`${key()}_catalogue_${$('[data-type]').value||'all'}_${$('[data-dispatch]').value||'all'}`;
 const say=s=>$('[data-status]').textContent=s;
 const meter=(done,total)=>{const bar=$('[data-progress]');bar.max=Math.max(1,total);bar.value=done;$('[data-count]').textContent=total?`${done} / ${total} · ${Math.round(done/total*100)}%`:'';};
 const totals=j=>{const verified=j.items.filter(i=>i.state==='complete').length,skipped=j.items.filter(i=>i.state==='skipped').length;meter(verified+skipped,j.items.length);return `${verified+skipped} of ${j.items.length} processed · ${verified} verified · ${skipped} skipped`;};
 const save=async j=>{const value=JSON.stringify(j);localStorage.setItem(key(),value);if(localStorage.getItem(key())!==value)throw Error('Could not save icon replacement progress.');};
 const render=()=>{
  const host=$('[data-results]');host.replaceChildren();for(const row of job?.items||preview?.items||[]){const label=document.createElement('label'),check=document.createElement('input'),text=document.createElement('span');check.type='checkbox';check.checked=row.selected!==false;check.disabled=iconBusy||Boolean(job);check.setAttribute('aria-label',`Select ${row.name}`);check.onchange=()=>{row.selected=check.checked;render();};text.textContent=`${row.name} · ${row.error||row.detail||row.state||'Ready'}`;label.append(check,text);host.append(label);}
  for(const tag of ['type','dispatch','scan','preview','clear'])$('[data-'+tag+']').disabled=iconBusy||Boolean(job&&job.state!=='complete'&&tag!=='clear');
  $('[data-run]').disabled=iconBusy||Boolean(job)||!preview?.items.some(i=>i.selected!==false);
  $('[data-resume]').disabled=iconBusy||!job||job.state==='complete';$('[data-pause]').disabled=!iconBusy;$('[data-skip]').disabled=iconBusy||!job?.items.some(i=>i.state==='writing');
  for(const b of d.querySelectorAll('.icons button'))b.disabled=iconBusy||Boolean(job);
 };
 const identity=async()=>{const id=String((await api.account()).user_id);if(account&&account!==id)throw Error('Game account changed. Reopen the tool.');account=id;};
 const guard=async fn=>{if(iconBusy)return;iconBusy=true;iconStop=false;const panel=$('.progress-panel');panel.dataset.working='true';$('[data-phase]').textContent='Working';$('[data-current]').textContent='';$('[data-progress]').removeAttribute('value');$('[data-count]').textContent='';const started=Date.now();const clock=()=>{$('[data-elapsed]').textContent=`${Math.floor((Date.now()-started)/1000)}s elapsed`;};clock();const ticker=setInterval(clock,1000);let failed=false;render();try{await identity();if(!navigator.locks?.request)throw Error('This browser cannot lock Operations across tabs.');await navigator.locks.request('mcms-hospital-upgrades',{ifAvailable:true},async lock=>{if(!lock)throw Error('Another Operations task is running in another tab.');await navigator.locks.request('mcms-home-response-build',{ifAvailable:true},async buildLock=>{if(!buildLock)throw Error('Home Response Builder is running in another tab.');await fn();});});}catch(e){failed=true;say(e.message);}finally{clearInterval(ticker);clock();if(!$('[data-progress]').hasAttribute('value'))meter(0,0);panel.dataset.working='false';$('[data-phase]').textContent=failed?'Needs attention':job?.state==='complete'?'Complete':job?.state==='paused'?'Paused':'Ready';if(failed)$('[data-current]').textContent='No further buildings will be changed until you review this.';iconBusy=false;render();}};
 const pickers=()=>{for(const side of ['from','to']){const host=$('[data-'+side+']');host.replaceChildren();for(const group of catalogue?.groups||[]){const b=document.createElement('button'),img=document.createElement('img'),label=document.createElement('span');img.src=group.url;img.alt='Station icon';img.loading='lazy';label.textContent=`${group.items.length} building${group.items.length===1?'':'s'}`;b.setAttribute('aria-label',`${side==='from'?'Replace':'Use'} icon used by ${group.items[0]?.name||'building'} and matching buildings`);b.setAttribute('aria-pressed',String((side==='from'?from:to)===group.key));b.append(img,label);b.onclick=()=>{if(side==='from')from=group.key;else to=group.key;preview=null;pickers();render();};host.append(b);}}};
 const restore=()=>{preview=null;from='';to='';try{catalogue=JSON.parse(localStorage.getItem(cacheKey())||'null');}catch{catalogue=null;}pickers();say(catalogue?`Saved catalogue from ${new Date(catalogue.savedAt).toLocaleString()}. Refresh to check changes.`:'No saved icons in this scope. Scan to create a catalogue.');render();};
 const scan=async()=>{say('Loading buildings for the selected scope…');records=await api.list();catalogue=await scanIcons(api,iconScope(records,$('[data-type]').value,$('[data-dispatch]').value),{stopped:()=>iconStop,progress:(n,total)=>{meter(n,total);say(`Scanning icons: ${n} of ${total} images checked`);$('[data-current]').textContent='Up to four image checks run together. No buildings are changed during scanning.';}});try{localStorage.setItem(cacheKey(),JSON.stringify(catalogue));}catch{say('Catalogue could not be saved in this browser.');}pickers();say(`${catalogue.groups.length} distinct icons · ${catalogue.unavailable.length} unreadable buildings excluded.`);};
 $('[data-close]').onclick=()=>d.close();$('[data-pause]').onclick=()=>{iconStop=true;say('Pausing after the current building…');};$('[data-type]').onchange=restore;$('[data-dispatch]').onchange=restore;
 $('[data-scan]').onclick=()=>guard(async()=>{job=null;preview=null;await scan();});
 $('[data-preview]').onclick=()=>guard(async()=>{preview=null;if(!from||!to||from===to)throw Error('Choose two different icons.');await scan();const original=catalogue.groups.find(g=>g.key===from),replacement=catalogue.groups.find(g=>g.key===to);if(!original||!replacement)throw Error('A chosen icon is no longer in this scope. Select icons again.');preview={schema:1,account,from,to,sourceId:replacement.sourceId,state:'ready',items:original.items.map(i=>({...i,state:'pending',selected:true}))};say(`${preview.items.length} matching buildings. Review the list and deselect any you want to keep.`);});
 const execute=async()=>{await runIconReplacement(job,api,{save,stopped:()=>iconStop,stage:(action,item)=>{say(action+'…');$('[data-current]').textContent=item?`Current building: ${item.name}`:'Preparing the selected replacement image';totals(job);},progress:j=>{say(totals(j));render();}});say(`${job.state}: ${totals(job)}.`);$('[data-current]').textContent=job.state==='complete'?'All selected buildings have been processed.':'Progress saved. Use Review & resume to continue.';};
 $('[data-run]').onclick=()=>guard(async()=>{if(!preview)return;const items=preview.items.filter(i=>i.selected!==false);if(!items.length||!window.confirm(`Replace the selected original icon on ${items.length} buildings with the selected replacement?\nOnly buildings still using that original icon will change. Names, dispatch assignments and other building settings are preserved.`))return;const stored=JSON.parse(localStorage.getItem(key())||'null');if(stored&&stored.state!=='complete')throw Error('A saved replacement plan already exists. Review & resume it first.');job={...preview,items};await save(job);preview=null;await execute();});
 $('[data-resume]').onclick=()=>guard(async()=>{job=JSON.parse(localStorage.getItem(key())||'null');if(job&&window.confirm('Resume this saved icon replacement plan? Completed buildings are verified or skipped; uncertain uploads are never repeated automatically.'))await execute();});
 $('[data-skip]').onclick=()=>guard(async()=>{job=JSON.parse(localStorage.getItem(key())||'null');const unresolved=job?.items.filter(i=>i.state==='writing')||[];if(!unresolved.length)return;if(!window.confirm(`Leave ${unresolved.length} unresolved buildings unchanged by this task and skip them? Check their actual icons in the game. No upload will be retried, and any already-saved icon will remain.`))return;for(const item of unresolved){item.state='skipped';item.detail='Uncertain upload excluded by user';delete item.error;}job.state=job.items.every(i=>['complete','skipped'].includes(i.state))?'complete':'paused';await save(job);say('Unresolved buildings excluded. Review & resume any remaining work.');});
 $('[data-clear]').onclick=()=>guard(async()=>{job=JSON.parse(localStorage.getItem(key())||'null');if(job?.items.some(i=>i.state==='writing')){say('An upload is uncertain. Review & resume to verify it before discarding this plan.');return;}if(!window.confirm('Discard pending selections? Icons already changed will remain changed.'))return;localStorage.removeItem(key());job=null;preview=null;restore();});
 guard(async()=>{records=await api.list();const types=[...new Set(records.map(r=>String(r.typeId)))].sort((a,b)=>api.typeName(a).localeCompare(api.typeName(b)));for(const type of types)$('[data-type]').add(new Option(api.typeName(type),type));for(const r of records.filter(r=>String(r.typeId)==='7').sort((a,b)=>a.caption.localeCompare(b.caption)))$('[data-dispatch]').add(new Option(r.caption,String(r.id)));restore();job=JSON.parse(localStorage.getItem(key())||'null');if(job)say(`Saved ${job.state} replacement plan. Review & resume or discard pending selections.`);});
}
