// Reproducible listing layouts using the approved art and actual rendered toolkit
// DOM from the contract harness. All account/mission values are demo fixtures.
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '..');
const out = path.join(root, '.dev/store-assets');
fs.mkdirSync(out, {recursive:true});
let fixture = fs.readFileSync(path.join(root,'.dev/store-toolkit-preview.html'),'utf8');
fixture = fixture.replace('<link rel="stylesheet" href="/devlab/fixture.css">', `<style>${fs.readFileSync(path.join(root,'devlab/fixture.css'),'utf8')}</style>`);
fs.writeFileSync(path.join(out,'toolkit-demo.html'),fixture);
const brand = '../../extension/branding/blackout-command.png';
const style = '*{box-sizing:border-box}html,body{margin:0;background:#090c11;color:#f7f4ee;font-family:Arial,sans-serif}.canvas{position:relative;overflow:hidden;width:1280px;height:800px;background:radial-gradient(ellipse at 10% 25%,#312316,transparent 58%),#090c11;border-top:5px solid #ffb521}.kicker{color:#ffc46a;font-size:14px;letter-spacing:3px;font-weight:700}.side{position:absolute;top:48px;left:42px;width:280px}.brand{width:155px;height:155px;object-fit:contain}h1{font-size:41px;line-height:1.08;margin:22px 0}p{color:#b5bdc8;font-size:18px;line-height:1.55}.chip{display:inline-block;border:1px solid #795626;color:#ffcd81;border-radius:20px;font-size:12px;padding:8px 14px;letter-spacing:1px}.frame{position:absolute;left:355px;top:95px;width:880px;height:620px;border:1px solid #5a4931;border-radius:14px;overflow:hidden;box-shadow:0 30px 80px #0008;background:#111}.frame iframe{width:1100px;height:775px;transform:scale(.8);transform-origin:top left;border:0}.caption{position:absolute;left:355px;top:53px;color:#d8dce2;font-size:15px}.foot{position:absolute;bottom:23px;left:42px;color:#929ba7;font-size:13px;letter-spacing:.3px}';
fs.writeFileSync(path.join(out,'screenshot.html'),`<!doctype html><html><head><meta charset="utf-8"><style>${style}</style></head><body><main class="canvas"><section class="side"><img class="brand" src="${brand}" alt="Blackout Command"><div class="kicker">MISSIONCHIEF UK</div><h1>Map Command<br>Toolkit</h1><p>Your map.<br>Your missions.<br>Your command centre.</p><span class="chip">EARLY ACCESS · 0.1.3</span></section><div class="caption">Administration interface · demonstration data</div><div class="frame"><iframe src="toolkit-demo.html" title="Toolkit administration interface"></iframe></div><div class="foot">Independent community extension · Not affiliated with MissionChief · Review game actions before confirming</div></main></body></html>`);
fs.writeFileSync(path.join(out,'promo.html'),`<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;background:#090c11;color:#fff;font-family:Arial,sans-serif}.tile{width:440px;height:280px;position:relative;overflow:hidden;background:radial-gradient(ellipse at 75% 40%,#392311,transparent 65%),#090c11;border-top:3px solid #ffb521;padding:30px 24px}img{position:absolute;right:8px;top:46px;width:205px;height:205px;object-fit:contain}small{font-size:10px;letter-spacing:2px;color:#ffc878}h1{position:relative;font-size:31px;line-height:1.08;margin:25px 0 18px;z-index:1}p{font-size:12px;color:#bfc5ce;position:relative;z-index:1}.tag{position:absolute;bottom:20px;font-size:10px;letter-spacing:1px;color:#ffd99e}</style></head><body><main class="tile"><small>MISSIONCHIEF UK</small><img src="${brand}" alt=""><h1>MAP<br>COMMAND<br>TOOLKIT</h1><p>Map. Missions. Administration.</p><div class="tag">INDEPENDENT EXTENSION · EARLY ACCESS</div></main></body></html>`);
console.log(out);
