name: Temporary Issue 553 v8.1.4 Executor

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  paused:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo paused
